Cries:
	dba Cry_Gurdurr
	dba Cry_Espurr
	dba Cry_Slowpoke
	dba Cry_Kangaskhan
	dba Cry_Flareon
	dba Cry_Grimer
	dba Cry_Voltorb
	dba Cry_Muk
	dba Cry_Nidoqueen
	dba Cry_Rotom
	dba Cry_Timburr
	dba Cry_Mienfoo
	dba Cry_Seel
	dba Cry_Drowzee
	dba Cry_Magneton
	dba Cry_Eevee
	dba Cry_Meowth
	dba Cry_Rhydon
	dba Cry_Golem
	dba Cry_Sylveon
	dba Cry_Magnezone
	dba Cry_Lycanroc
	dba Cry_Zorua
	dba Cry_Togepi
	dba Cry_Persian
	dba Cry_Purrloin
	dba Cry_Swablu
	dba Cry_Lapras
	dba Cry_Zoroark
	dba Cry_Leafeon
	dba Cry_Sentret
	dba Cry_Luxray
	dba Cry_Krabby
	dba Cry_Flaaffy
	dba Cry_Porygon2
	dba Cry_Zangoose
	dba Cry_Vulpix
	dba Cry_Weepinbell
	dba Cry_Braixen
	dba Cry_Spinarak
	dba Cry_Heidreigon
	dba Cry_Girafarig
	dba Cry_Raikou
	dba Cry_Litten
	dba Cry_Cyndaquil
	dba Cry_Tyranitar
	dba Cry_Larvitar
	dba Cry_Slowking
	dba Cry_Abomasnow
	dba Cry_Chikorita
	dba Cry_Totodile
	dba Cry_Gligar
	dba Cry_Cleffa
	dba Cry_Slugma
	dba Cry_Ledyba
	dba Cry_Entei
	dba Cry_Wooper
	dba Cry_Doublade
	dba Cry_Ferrothorn
	dba Cry_Quilava
	dba Cry_Teddiursa
	dba Cry_Sunflora
	dba Cry_Incineroar
	dba Cry_Magcargo
	dba Cry_Pichu
	dba Cry_Aipom
	dba Cry_Dunsparce
	dba Cry_Litwick
