	const_def
	const PAL_TOWNMAP_BORDER   		; 0
	const PAL_TOWNMAP_LAKE_ASH 		; 1
	const PAL_TOWNMAP_MOUNTAIN 		; 2
	const PAL_TOWNMAP_CITY     		; 3
	const PAL_TOWNMAP_FOREST   		; 4
	const PAL_TOWNMAP_SWAMP    		; 5
	const PAL_TOWNMAP_VOLCANO_EDGE	; 6
	const PAL_TOWNMAP_VOLCANO  		; 7


townmappals: MACRO
rept _NARG / 2
	dn PAL_TOWNMAP_\2, PAL_TOWNMAP_\1
	shift
	shift
endr
ENDM

; gfx/pokegear/town_map.png
	townmappals MOUNTAIN,    MOUNTAIN,    VOLCANO,     VOLCANO,  VOLCANO,  VOLCANO_EDGE,BORDER,	  BORDER
	townmappals VOLCANO_EDGE,VOLCANO_EDGE,CITY,        LAKE_ASH, MOUNTAIN, MOUNTAIN, 	MOUNTAIN, FOREST
	townmappals VOLCANO_EDGE,VOLCANO,     VOLCANO,     VOLCANO,  VOLCANO,  VOLCANO,  	BORDER,   BORDER
	townmappals VOLCANO_EDGE,VOLCANO_EDGE,VOLCANO_EDGE,LAKE_ASH, LAKE_ASH, FOREST,   	FOREST,   FOREST
	townmappals VOLCANO_EDGE,VOLCANO,     VOLCANO,	   VOLCANO,  VOLCANO,  VOLCANO,  	BORDER,   BORDER
	townmappals VOLCANO_EDGE,VOLCANO_EDGE,VOLCANO_EDGE,LAKE_ASH, FOREST,   FOREST,   	FOREST,   FOREST
; gfx/pokegear/pokegear.png
	townmappals BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER
	townmappals BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER
	townmappals CITY,     CITY,     CITY,     CITY,     CITY,     CITY,     CITY,     CITY
	townmappals CITY,     CITY,     CITY,     CITY,     CITY,     CITY,     MOUNTAIN, BORDER
	townmappals CITY,     CITY,     CITY,     CITY,     CITY,     CITY,     CITY,     CITY
	townmappals BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER
; gfx/pokegear/town_map2.png
	townmappals SWAMP,    SWAMP,    SWAMP,    SWAMP,    LAKE_ASH, LAKE_ASH, LAKE_ASH, FOREST
	townmappals FOREST,   FOREST,   MOUNTAIN, MOUNTAIN, FOREST,   FOREST,   FOREST,   FOREST
	townmappals SWAMP,    SWAMP,    SWAMP,    LAKE_ASH, LAKE_ASH, LAKE_ASH, LAKE_ASH, MOUNTAIN
	townmappals FOREST,   MOUNTAIN, MOUNTAIN, MOUNTAIN, FOREST,   FOREST,   FOREST,   MOUNTAIN


