AnimationPointers:
	dw EeveeAnimation
	dw VaporeonAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw LeafeonAnimation
	dw GlaceonAnimation
	dw SylveonAnimation
	dw ZoruaAnimation
	dw ZoroarkAnimation
	dw RockruffAnimation
	dw LycanrocAnimation
	dw MimikyuAnimation
	dw MagnemiteAnimation
	dw MagnetonAnimation
	dw MagnezoneAnimation
	dw PorygonAnimation
	dw Porygon2Animation
	dw PorygonZAnimation
	dw MeowthAnimation
	dw PersianAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw TogekissAnimation
	dw RotomAnimation
	dw ChinglingAnimation
	dw ChimechoAnimation
	dw EspurrAnimation
	dw Meowstic_MAnimation
	dw TimburrAnimation
	dw GurdurrAnimation
	dw ConkeldurrAnimation
	dw DittoAnimation
	dw PurrloinAnimation
	dw LiepardAnimation
	dw VulpixAnimation
	dw MukAnimation
	dw Nidoran_MAnimation
	dw NidorinoAnimation
	dw NidorinaAnimation
	dw NidokingAnimation
	dw NidoqueenAnimation
	dw SeviperAnimation
	dw ZangooseAnimation
	dw SentretAnimation
	dw FurretAnimation
	dw SwabluAnimation
	dw AltariaAnimation
	dw MienfooAnimation
	dw MienshaoAnimation
	dw HawluchaAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw ShinxAnimation
	dw LuxioAnimation
	dw LuxrayAnimation
	dw SandshrewAnimation
	dw SandslashAnimation
	dw CutieflyAnimation
	dw RibombeeAnimation
	dw FlabebeAnimation
	dw FloetteAnimation
	dw FlorgesAnimation
	dw IgglybuffAnimation
	dw JigglypuffAnimation
	dw WigglytuffAnimation
	dw ChespinAnimation
	dw QuilladinAnimation
	dw ChesnaughtAnimation
	dw DeerlingAnimation
	dw SawsbuckAnimation
	dw GeodudeAnimation
	dw GravelerAnimation
	dw GolemAnimation
	dw PonytaAnimation
	dw RapidashAnimation
	dw SlowpokeAnimation
	dw SlowbroAnimation
	dw Placeholder1Animation
	dw MagnetonAnimation
	dw FarfetchDAnimation
	dw DoduoAnimation
	dw DodrioAnimation
	dw SeelAnimation
	dw DewgongAnimation
	dw GrimerAnimation
	dw MukAnimation
	dw ShellderAnimation
	dw CloysterAnimation
	dw GastlyAnimation
	dw HaunterAnimation
	dw GengarAnimation
	dw OnixAnimation
	dw DrowzeeAnimation
	dw HypnoAnimation
	dw KrabbyAnimation
	dw KinglerAnimation
	dw VoltorbAnimation
	dw ElectrodeAnimation
	dw ExeggcuteAnimation
	dw ExeggutorAnimation
	dw CuboneAnimation
	dw MarowakAnimation
	dw HitmonleeAnimation
	dw HitmonchanAnimation
	dw LickitungAnimation
	dw KoffingAnimation
	dw WeezingAnimation
	dw RhyhornAnimation
	dw RhydonAnimation
	dw ChanseyAnimation
	dw TangelaAnimation
	dw KangaskhanAnimation
	dw HorseaAnimation
	dw SeadraAnimation
	dw GoldeenAnimation
	dw SeakingAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw MrMimeAnimation
	dw ScytherAnimation
	dw JynxAnimation
	dw ElectabuzzAnimation
	dw MagmarAnimation
	dw PinsirAnimation
	dw TaurosAnimation
	dw MagikarpAnimation
	dw GyaradosAnimation
	dw LaprasAnimation
	dw DewpiderAnimation
	dw EeveexAnimation
	dw VaporeonxAnimation
	dw JolteonxAnimation
	dw FlareonxAnimation
	dw Place3Animation
	dw OmanyteAnimation
	dw OmastarAnimation
	dw KabutoAnimation
	dw KabutopsAnimation
	dw AerodactylAnimation
	dw SnorlaxAnimation
	dw DwebbleAnimation
	dw CrustleAnimation
	dw TyrogueAnimation
	dw DratiniAnimation
	dw DragonairAnimation
	dw DragoniteAnimation
	dw RioluAnimation
	dw LucarioAnimation
	dw ChikoritaAnimation
	dw BayleefAnimation
	dw MeganiumAnimation
	dw AbomasnowAnimation
	dw FerroseedAnimation
	dw FerrothornAnimation
	dw TotodileAnimation
	dw CroconawAnimation
	dw FeraligatrAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw NoctowlAnimation
	dw LedybaAnimation
	dw LedianAnimation
	dw SpinarakAnimation
	dw AriadosAnimation
	dw CrobatAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw PichuAnimation
	dw CleffaAnimation
	dw ZweilousAnimation
	dw HeidreigonAnimation
	dw CyndaquilAnimation
	dw QuilavaAnimation
	dw TyphlosionAnimation
	dw LittenAnimation
	dw TorracatAnimation
	dw IncineroarAnimation
	dw FennekinAnimation
	dw BraixenAnimation
	dw DelphoxAnimation
	dw VulpixAnimation
	dw NinetalesAnimation
	dw HoppipAnimation
	dw SkiploomAnimation
	dw JumpluffAnimation
	dw AipomAnimation
	dw SunkernAnimation
	dw SunfloraAnimation
	dw YanmaAnimation
	dw WooperAnimation
	dw QuagsireAnimation
	dw EspeonxAnimation
	dw UmbreonxAnimation
	dw MurkrowAnimation
	dw SlowkingAnimation
	dw MisdreavusAnimation
	dw CarbinkAnimation
	dw WobbuffetAnimation
	dw GirafarigAnimation
	dw PinecoAnimation
	dw ForretressAnimation
	dw DunsparceAnimation
	dw GligarAnimation
	dw SteelixAnimation
	dw SnubbullAnimation
	dw GranbullAnimation
	dw QwilfishAnimation
	dw ScizorAnimation
	dw UnownAnimation
	dw NatuAnimation
	dw XatuAnimation
	dw SigilyphAnimation
	dw DrillburAnimation
	dw ExcadrillAnimation
	dw BaltoyAnimation
	dw ClaydolAnimation
	dw GolettAnimation
	dw GolurkAnimation
	dw BronzorAnimation
	dw BronzongAnimation
	dw HonedgeAnimation
	dw DoubladeAnimation
	dw AegislashAnimation
	dw PawniardAnimation
	dw BisharpAnimation
	dw YamaskAnimation
	dw CofagrigusAnimation
	dw LitwickAnimation
	dw LampentAnimation
	dw ChandelureAnimation
	dw SpiritombAnimation
	dw DuskullAnimation
	dw DusclopsAnimation
	dw DusknoirAnimation
	dw ArticunoAnimation
	dw ZapdosAnimation
	dw MoltresAnimation
	dw SuicuneAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw LatiasAnimation
	dw LatiosAnimation
	dw SilvallyAnimation
	dw MagearnaAnimation
	dw ShayminAnimation
	dw CelebiAnimation
	dw ZygardeAnimation
	dw MewAnimation
	dw MewtwoAnimation
