AnimationPointers:
	dw EeveeAnimation
	dw MagikarpAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw LeafeonAnimation
	dw GlaceonAnimation
	dw SylveonAnimation
	dw ZoruaAnimation
	dw ZoroarkAnimation
	dw RockruffAnimation
	dw LycanrocAnimation
	dw MimikyuAnimation
	dw MagnemiteAnimation
	dw MagnetonAnimation
	dw MagnezoneAnimation
	dw PorygonAnimation
	dw Porygon2Animation
	dw PorygonZAnimation
	dw MeowthAnimation
	dw PersianAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw TogekissAnimation
	dw RotomAnimation
	dw ChinglingAnimation
	dw ChimechoAnimation
	dw EspurrAnimation
	dw Meowstic_MAnimation
	dw TimburrAnimation
	dw GurdurrAnimation
	dw ConkeldurrAnimation
	dw DittoAnimation
	dw PurrloinAnimation
	dw LiepardAnimation
	dw VulpixAnimation
	dw MukAnimation
	dw Nidoran_MAnimation
	dw NidorinoAnimation
	dw NidorinaAnimation
	dw NidokingAnimation
	dw NidoqueenAnimation
	dw SeviperAnimation
	dw ZangooseAnimation
	dw SentretAnimation
	dw FurretAnimation
	dw SwabluAnimation
	dw AltariaAnimation
	dw MienfooAnimation
	dw MienshaoAnimation
	dw HawluchaAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw ShinxAnimation
	dw LuxioAnimation
	dw LuxrayAnimation
	dw SandshrewAnimation
	dw SandslashAnimation
	dw CutieflyAnimation
	dw RibombeeAnimation
	dw FlabebeAnimation
	dw FloetteAnimation
	dw FlorgesAnimation
	dw IgglybuffAnimation
	dw JigglypuffAnimation
	dw WigglytuffAnimation
	dw ChespinAnimation
	dw QuilladinAnimation
	dw ChesnaughtAnimation
	dw DeerlingAnimation
	dw SawsbuckAnimation
	dw CottoneeAnimation
	dw WhimsicottAnimation
	dw FoongusAnimation
	dw AmoongusAnimation
	dw PhantumpAnimation
	dw TrevanantAnimation
	dw BonslyAnimation
	dw SudowoodoAnimation
	dw PassimianAnimation
	dw StuffulAnimation
	dw BewearAnimation
	dw GirafarigAnimation
	dw HeracrossAnimation
	dw LedybaAnimation
	dw LedianAnimation
	dw JoltikAnimation
	dw GalvantulaAnimation
	dw PinecoAnimation
	dw ForretressAnimation
	dw YanmaAnimation
	dw YanmegaAnimation
	dw ScytherAnimation
	dw ScizorAnimation
	dw HypnoAnimation
	dw KrabbyAnimation
	dw KinglerAnimation
	dw VoltorbAnimation
	dw ElectrodeAnimation
	dw ExeggcuteAnimation
	dw ExeggutorAnimation
	dw CuboneAnimation
	dw MarowakAnimation
	dw SandileAnimation
	dw KrokorokAnimation
	dw LickitungAnimation
	dw KoffingAnimation
	dw WeezingAnimation
	dw RhyhornAnimation
	dw RhydonAnimation
	dw ChanseyAnimation
	dw TangelaAnimation
	dw KangaskhanAnimation
	dw HorseaAnimation
	dw SeadraAnimation
	dw GoldeenAnimation
	dw SeakingAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw MrMimeAnimation
	dw SamurottAnimation
	dw JynxAnimation
	dw ElectabuzzAnimation
	dw MagmarAnimation
	dw PinsirAnimation
	dw AzumarillAnimation
	dw MagikarpAnimation
	dw AnorithAnimation
	dw ArmaldoAnimation
	dw DewpiderAnimation
	dw AraquanidAnimation
	dw MagikarpxAnimation
	dw GyaradosAnimation
	dw FeebasAnimation
	dw MiloticAnimation
	dw FinneonAnimation
	dw LumineonAnimation
	dw QwilfishAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw StunfiskAnimation
	dw DwebbleAnimation
	dw CrustleAnimation
	dw TyrogueAnimation
	dw HitmonchanAnimation
	dw HitmonleeAnimation
	dw HitmontopAnimation
	dw RioluAnimation
	dw LucarioAnimation
	dw ChikoritaAnimation
	dw MedichamAnimation
	dw SnoverAnimation
	dw AbomasnowAnimation
	dw FerroseedAnimation
	dw FerrothornAnimation
	dw ShuckleAnimation
	dw NosepassAnimation
	dw ProbopassAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw NoibatAnimation
	dw NoivernAnimation
	dw DruddigonAnimation
	dw AxewAnimation
	dw FraxureAnimation
	dw HaxorusAnimation
	dw Jangmo_oAnimation
	dw Hakamo_oAnimation
	dw Kommo_oAnimation
	dw DeinoAnimation
	dw ZweilousAnimation
	dw HeidreigonAnimation
	dw CyndaquilAnimation
	dw QuilavaAnimation
	dw TyphlosionAnimation
	dw LittenAnimation
	dw TorracatAnimation
	dw IncineroarAnimation
	dw FennekinAnimation
	dw BraixenAnimation
	dw DelphoxAnimation
	dw VulpixAnimation
	dw NinetalesAnimation
	dw SlugmaAnimation
	dw MagcargoAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw FletchlingAnimation
	dw FletchinderAnimation
	dw TalonflameAnimation
	dw HeatmorAnimation
	dw DurantAnimation
	dw ArchenAnimation
	dw ArcheopsAnimation
	dw RoggenrolaAnimation
	dw BoldoreAnimation
	dw GigalithAnimation
	dw CarbinkAnimation
	dw AmauraAnimation
	dw AurorusAnimation
	dw SneaselAnimation
	dw WeavileAnimation
	dw CryogonalAnimation
	dw SnowruntAnimation
	dw GlalieAnimation
	dw FrosslassAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw MamoswineAnimation
	dw UnownAnimation
	dw NatuAnimation
	dw XatuAnimation
	dw SigilyphAnimation
	dw DrillburAnimation
	dw ExcadrillAnimation
	dw BaltoyAnimation
	dw ClaydolAnimation
	dw GolettAnimation
	dw GolurkAnimation
	dw BronzorAnimation
	dw BronzongAnimation
	dw HonedgeAnimation
	dw DoubladeAnimation
	dw AegislashAnimation
	dw PawniardAnimation
	dw BisharpAnimation
	dw YamaskAnimation
	dw CofagrigusAnimation
	dw LitwickAnimation
	dw LampentAnimation
	dw ChandelureAnimation
	dw SpiritombAnimation
	dw DuskullAnimation
	dw DusclopsAnimation
	dw DusknoirAnimation
	dw ArticunoAnimation
	dw ZapdosAnimation
	dw MoltresAnimation
	dw SuicuneAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw LatiasAnimation
	dw LatiosAnimation
	dw SilvallyAnimation
	dw MagearnaAnimation
	dw ShayminAnimation
	dw CelebiAnimation
	dw ZygardeAnimation
	dw MewAnimation
	dw MewtwoAnimation
