BitmasksPointers:
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw LeafeonBitmasks
	dw GlaceonBitmasks
	dw SylveonBitmasks
	dw ZoruaBitmasks
	dw ZoroarkBitmasks
	dw RockruffBitmasks
	dw LycanrocBitmasks
	dw MimikyuBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw MagnezoneBitmasks
	dw PorygonBitmasks
	dw Porygon2Bitmasks
	dw PorygonZBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw TogekissBitmasks
	dw RotomBitmasks
	dw ChinglingBitmasks
	dw ChimechoBitmasks
	dw EspurrBitmasks
	dw Meowstic_MBitmasks
	dw TimburrBitmasks
	dw GurdurrBitmasks
	dw ConkeldurrBitmasks
	dw DittoBitmasks
	dw PurrloinBitmasks
	dw LiepardBitmasks
	dw VulpixBitmasks
	dw MukBitmasks
	dw Nidoran_MBitmasks
	dw NidorinoBitmasks
	dw NidorinaBitmasks
	dw NidokingBitmasks
	dw NidoqueenBitmasks
	dw SeviperBitmasks
	dw ZangooseBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw SwabluBitmasks
	dw AltariaBitmasks
	dw MienfooBitmasks
	dw MienshaoBitmasks
	dw HawluchaBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw ShinxBitmasks
	dw LuxioBitmasks
	dw LuxrayBitmasks
	dw SandshrewBitmasks
	dw SandslashBitmasks
	dw CutieflyBitmasks
	dw RibombeeBitmasks
	dw FlabebeBitmasks
	dw FloetteBitmasks
	dw FlorgesBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw Placeholder1Bitmasks
	dw MagnetonBitmasks
	dw FarfetchDBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw GrimerBitmasks
	dw MukBitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw DrowzeeBitmasks
	dw HypnoBitmasks
	dw KrabbyBitmasks
	dw KinglerBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw HitmonleeBitmasks
	dw HitmonchanBitmasks
	dw LickitungBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw ChanseyBitmasks
	dw TangelaBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw GoldeenBitmasks
	dw SeakingBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MrMimeBitmasks
	dw ScytherBitmasks
	dw JynxBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw PinsirBitmasks
	dw TaurosBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw LaprasBitmasks
	dw DewpiderBitmasks
	dw EeveexBitmasks
	dw VaporeonxBitmasks
	dw JolteonxBitmasks
	dw FlareonxBitmasks
	dw Place3Bitmasks
	dw OmanyteBitmasks
	dw OmastarBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw AerodactylBitmasks
	dw SnorlaxBitmasks
	dw DwebbleBitmasks
	dw CrustleBitmasks
	dw TyrogueBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw RioluBitmasks
	dw LucarioBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw AbomasnowBitmasks
	dw FerroseedBitmasks
	dw FerrothornBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw NoctowlBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw PichuBitmasks
	dw CleffaBitmasks
	dw IgglybuffBitmasks
	dw HeidreigonBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw LittenBitmasks
	dw TorracatBitmasks
	dw IncineroarBitmasks
	dw FennekinBitmasks
	dw BraixenBitmasks
	dw DelphoxBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw HoppipBitmasks
	dw SkiploomBitmasks
	dw JumpluffBitmasks
	dw AipomBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw YanmaBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw EspeonxBitmasks
	dw UmbreonxBitmasks
	dw MurkrowBitmasks
	dw SlowkingBitmasks
	dw MisdreavusBitmasks
	dw CarbinkBitmasks
	dw WobbuffetBitmasks
	dw GirafarigBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw DunsparceBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw QwilfishBitmasks
	dw ScizorBitmasks
	dw UnownBitmasks
	dw HeracrossBitmasks
	dw SneaselBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw GolurkBitmasks
	dw BronzorBitmasks
	dw BronzongBitmasks
	dw HonedgeBitmasks
	dw DoubladeBitmasks
	dw AegislashBitmasks
	dw PawniardBitmasks
	dw BisharpBitmasks
	dw YamaskBitmasks
	dw CofagrigusBitmasks
	dw LitwickBitmasks
	dw LampentBitmasks
	dw ChandelureBitmasks
	dw SpiritombBitmasks
	dw DuskullBitmasks
	dw DusclopsBitmasks
	dw DusknoirBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw SuicuneBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw LatiasBitmasks
	dw LatiosBitmasks
	dw SilvallyBitmasks
	dw MagearnaBitmasks
	dw ShayminBitmasks
	dw CelebiBitmasks
	dw ZygardeBitmasks
	dw MewBitmasks
	dw MewtwoBitmasks

