FramesPointers:
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw LeafeonFrames
	dw GlaceonFrames
	dw SylveonFrames
	dw ZoruaFrames
	dw ZoroarkFrames
	dw RockruffFrames
	dw LycanrocFrames
	dw MimikyuFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw MagnezoneFrames
	dw PorygonFrames
	dw Porygon2Frames
	dw PorygonZFrames
	dw MeowthFrames
	dw PersianFrames
	dw TogepiFrames
	dw TogeticFrames
	dw TogekissFrames
	dw RotomFrames
	dw ChinglingFrames
	dw ChimechoFrames
	dw EspurrFrames
	dw Meowstic_MFrames
	dw TimburrFrames
	dw GurdurrFrames
	dw ConkeldurrFrames
	dw DittoFrames
	dw PurrloinFrames
	dw LiepardFrames
	dw VulpixFrames
	dw MukFrames
	dw Nidoran_MFrames
	dw NidorinoFrames
	dw NidorinaFrames
	dw NidokingFrames
	dw NidoqueenFrames
	dw SeviperFrames
	dw ZangooseFrames
	dw SentretFrames
	dw FurretFrames
	dw SwabluFrames
	dw AltariaFrames
	dw MienfooFrames
	dw MienshaoFrames
	dw HawluchaFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw ShinxFrames
	dw LuxioFrames
	dw LuxrayFrames
	dw SandshrewFrames
	dw SandslashFrames
	dw PoliwhirlFrames
	dw PoliwrathFrames
	dw AbraFrames
	dw KadabraFrames
	dw AlakazamFrames
	dw MachopFrames
	dw MachokeFrames
	dw MachampFrames
	dw BellsproutFrames
	dw WeepinbellFrames
	dw VictreebelFrames
	dw TentacoolFrames
	dw TentacruelFrames
	dw GeodudeFrames
	dw GravelerFrames
	dw GolemFrames
	dw PonytaFrames
	dw RapidashFrames
	dw SlowpokeFrames
	dw SlowbroFrames
	dw Placeholder1Frames
	dw MagnetonFrames
	dw FarfetchDFrames
	dw DoduoFrames
	dw DodrioFrames
	dw SeelFrames
	dw DewgongFrames
	dw GrimerFrames
	dw MukFrames
	dw ShellderFrames
	dw CloysterFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw OnixFrames
	dw DrowzeeFrames
	dw HypnoFrames
	dw KrabbyFrames
	dw KinglerFrames
	dw VoltorbFrames
	dw ElectrodeFrames
	dw ExeggcuteFrames
	dw ExeggutorFrames
	dw CuboneFrames
	dw MarowakFrames
	dw HitmonleeFrames
	dw HitmonchanFrames
	dw LickitungFrames
	dw KoffingFrames
	dw WeezingFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw ChanseyFrames
	dw TangelaFrames
	dw KangaskhanFrames
	dw HorseaFrames
	dw SeadraFrames
	dw GoldeenFrames
	dw SeakingFrames
	dw StaryuFrames
	dw StarmieFrames
	dw MrMimeFrames
	dw ScytherFrames
	dw JynxFrames
	dw ElectabuzzFrames
	dw MagmarFrames
	dw PinsirFrames
	dw TaurosFrames
	dw MagikarpFrames
	dw GyaradosFrames
	dw LaprasFrames
	dw DewpiderFrames
	dw EeveexFrames
	dw VaporeonxFrames
	dw JolteonxFrames
	dw FlareonxFrames
	dw Place3Frames
	dw OmanyteFrames
	dw OmastarFrames
	dw KabutoFrames
	dw KabutopsFrames
	dw AerodactylFrames
	dw SnorlaxFrames
	dw DwebbleFrames
	dw CrustleFrames
	dw TyrogueFrames
	dw DratiniFrames
	dw DragonairFrames
	dw DragoniteFrames
	dw RioluFrames
	dw LucarioFrames
	dw ChikoritaFrames
	dw BayleefFrames
	dw MeganiumFrames
	dw AbomasnowFrames
	dw FerroseedFrames
	dw FerrothornFrames
	dw TotodileFrames
	dw CroconawFrames
	dw FeraligatrFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw NoctowlFrames
	dw LedybaFrames
	dw LedianFrames
	dw SpinarakFrames
	dw AriadosFrames
	dw CrobatFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw PichuFrames
	dw CleffaFrames
	dw IgglybuffFrames
	dw HeidreigonFrames
	dw CyndaquilFrames
	dw QuilavaFrames
	dw TyphlosionFrames
	dw LittenFrames
	dw TorracatFrames
	dw IncineroarFrames
	dw FennekinFrames
	dw BraixenFrames
	dw DelphoxFrames
	dw VulpixFrames
	dw NinetalesFrames
	dw HoppipFrames
	dw SkiploomFrames
	dw JumpluffFrames
	dw AipomFrames
	dw SunkernFrames
	dw SunfloraFrames
	dw YanmaFrames
	dw WooperFrames
	dw QuagsireFrames
	dw EspeonxFrames
	dw UmbreonFrames
	dw MurkrowFrames
	dw SlowkingFrames
	dw MisdreavusFrames
	dw CarbinkFrames
	dw WobbuffetFrames
	dw GirafarigFrames
	dw PinecoFrames
	dw ForretressFrames
	dw DunsparceFrames
	dw GligarFrames
	dw SteelixFrames
	dw SnubbullFrames
	dw GranbullFrames
	dw QwilfishFrames
	dw ScizorFrames
	dw UnownFrames
	dw HeracrossFrames
	dw SneaselFrames
	dw TeddiursaFrames
	dw UrsaringFrames
	dw SlugmaFrames
	dw MagcargoFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw GolurkFrames
	dw BronzorFrames
	dw BronzongFrames
	dw HonedgeFrames
	dw DoubladeFrames
	dw AegislashFrames
	dw PawniardFrames
	dw BisharpFrames
	dw YamaskFrames
	dw CofagrigusFrames
	dw LitwickFrames
	dw LampentFrames
	dw ChandelureFrames
	dw SpiritombFrames
	dw DuskullFrames
	dw DusclopsFrames
	dw DusknoirFrames
	dw ArticunoFrames
	dw ZapdosFrames
	dw MoltresFrames
	dw SuicuneFrames
	dw RaikouFrames
	dw EnteiFrames
	dw LatiasFrames
	dw LatiosFrames
	dw SilvallyFrames
	dw MagearnaFrames
	dw ShayminFrames
	dw CelebiFrames
	dw ZygardeFrames
	dw MewFrames
	dw MewtwoFrames
