FramesPointers:
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw LeafeonFrames
	dw GlaceonFrames
	dw SylveonFrames
	dw ZoruaFrames
	dw ZoroarkFrames
	dw RockruffFrames
	dw LycanrocFrames
	dw MimikyuFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw MagnezoneFrames
	dw PorygonFrames
	dw Porygon2Frames
	dw PorygonZFrames
	dw MeowthFrames
	dw PersianFrames
	dw TogepiFrames
	dw TogeticFrames
	dw TogekissFrames
	dw RotomFrames
	dw ChinglingFrames
	dw ChimechoFrames
	dw EspurrFrames
	dw Meowstic_MFrames
	dw TimburrFrames
	dw GurdurrFrames
	dw ConkeldurrFrames
	dw DittoFrames
	dw PurrloinFrames
	dw LiepardFrames
	dw VulpixFrames
	dw MukFrames
	dw Nidoran_MFrames
	dw NidorinoFrames
	dw NidorinaFrames
	dw NidokingFrames
	dw NidoqueenFrames
	dw SeviperFrames
	dw ZangooseFrames
	dw SentretFrames
	dw FurretFrames
	dw SwabluFrames
	dw AltariaFrames
	dw MienfooFrames
	dw MienshaoFrames
	dw HawluchaFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw ShinxFrames
	dw LuxioFrames
	dw LuxrayFrames
	dw SandshrewFrames
	dw SandslashFrames
	dw CutieflyFrames
	dw RibombeeFrames
	dw FlabebeFrames
	dw FloetteFrames
	dw FlorgesFrames
	dw IgglybuffFrames
	dw JigglypuffFrames
	dw WigglytuffFrames
	dw ChespinFrames
	dw QuilladinFrames
	dw ChesnaughtFrames
	dw DeerlingFrames
	dw SawsbuckFrames
	dw CottoneeFrames
	dw WhimsicottFrames
	dw FoongusFrames
	dw AmoongusFrames
	dw PhantumpFrames
	dw TrevanantFrames
	dw BonslyFrames
	dw SudowoodoFrames
	dw PassimianFrames
	dw StuffulFrames
	dw BewearFrames
	dw GirafarigFrames
	dw HeracrossFrames
	dw LedybaFrames
	dw LedianFrames
	dw JoltikFrames
	dw GalvantulaFrames
	dw PinecoFrames
	dw ForretressFrames
	dw HaunterFrames
	dw GengarFrames
	dw OnixFrames
	dw DrowzeeFrames
	dw HypnoFrames
	dw KrabbyFrames
	dw KinglerFrames
	dw VoltorbFrames
	dw ElectrodeFrames
	dw ExeggcuteFrames
	dw ExeggutorFrames
	dw CuboneFrames
	dw MarowakFrames
	dw HitmonleeFrames
	dw HitmonchanFrames
	dw LickitungFrames
	dw KoffingFrames
	dw WeezingFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw ChanseyFrames
	dw TangelaFrames
	dw KangaskhanFrames
	dw HorseaFrames
	dw SeadraFrames
	dw GoldeenFrames
	dw SeakingFrames
	dw StaryuFrames
	dw StarmieFrames
	dw MrMimeFrames
	dw ScytherFrames
	dw JynxFrames
	dw ElectabuzzFrames
	dw MagmarFrames
	dw PinsirFrames
	dw AzumarillFrames
	dw MagikarpFrames
	dw AnorithFrames
	dw ArmaldoFrames
	dw DewpiderFrames
	dw AraquanidFrames
	dw VaporeonxFrames
	dw JolteonxFrames
	dw FlareonxFrames
	dw Place3Frames
	dw OmanyteFrames
	dw OmastarFrames
	dw KabutoFrames
	dw KabutopsFrames
	dw AerodactylFrames
	dw SnorlaxFrames
	dw DwebbleFrames
	dw CrustleFrames
	dw TyrogueFrames
	dw DratiniFrames
	dw DragonairFrames
	dw DragoniteFrames
	dw RioluFrames
	dw LucarioFrames
	dw ChikoritaFrames
	dw BayleefFrames
	dw MeganiumFrames
	dw AbomasnowFrames
	dw FerroseedFrames
	dw FerrothornFrames
	dw TotodileFrames
	dw CroconawFrames
	dw FeraligatrFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw NoctowlFrames
	dw NoivernFrames
	dw DruddigonFrames
	dw AxewFrames
	dw FraxureFrames
	dw HaxorusFrames
	dw Jangmo_oFrames
	dw Hakamo_oFrames
	dw Kommo_oFrames
	dw DeinoFrames
	dw ZweilousFrames
	dw HeidreigonFrames
	dw CyndaquilFrames
	dw QuilavaFrames
	dw TyphlosionFrames
	dw LittenFrames
	dw TorracatFrames
	dw IncineroarFrames
	dw FennekinFrames
	dw BraixenFrames
	dw DelphoxFrames
	dw VulpixFrames
	dw NinetalesFrames
	dw SlugmaFrames
	dw MagcargoFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw FletchlingFrames
	dw FletchinderFrames
	dw TalonflameFrames
	dw HeatmorFrames
	dw DurantFrames
	dw ArchenFrames
	dw UmbreonFrames
	dw RoggenrolaFrames
	dw BoldoreFrames
	dw GigalithFrames
	dw CarbinkFrames
	dw AmauraFrames
	dw AurorusFrames
	dw SneaselFrames
	dw WeavileFrames
	dw CryogonalFrames
	dw SnowruntFrames
	dw GlalieFrames
	dw FrosslassFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw MamoswineFrames
	dw UnownFrames
	dw NatuFrames
	dw XatuFrames
	dw SigilyphFrames
	dw DrillburFrames
	dw ExcadrillFrames
	dw BaltoyFrames
	dw ClaydolFrames
	dw GolettFrames
	dw GolurkFrames
	dw BronzorFrames
	dw BronzongFrames
	dw HonedgeFrames
	dw DoubladeFrames
	dw AegislashFrames
	dw PawniardFrames
	dw BisharpFrames
	dw YamaskFrames
	dw CofagrigusFrames
	dw LitwickFrames
	dw LampentFrames
	dw ChandelureFrames
	dw SpiritombFrames
	dw DuskullFrames
	dw DusclopsFrames
	dw DusknoirFrames
	dw ArticunoFrames
	dw ZapdosFrames
	dw MoltresFrames
	dw SuicuneFrames
	dw RaikouFrames
	dw EnteiFrames
	dw LatiasFrames
	dw LatiosFrames
	dw SilvallyFrames
	dw MagearnaFrames
	dw ShayminFrames
	dw CelebiFrames
	dw ZygardeFrames
	dw MewFrames
	dw MewtwoFrames
