AnimationIdlePointers:
	dw EeveeAnimationIdle
	dw VaporeonAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw LeafeonAnimationIdle
	dw GlaceonAnimationIdle
	dw SylveonAnimationIdle
	dw ZoruaAnimationIdle
	dw ZoroarkAnimationIdle
	dw RockruffAnimationIdle
	dw LycanrocAnimationIdle
	dw MimikyuAnimationIdle
	dw MagnemiteAnimationIdle
	dw MagnetonAnimationIdle
	dw MagnezoneAnimationIdle
	dw PorygonAnimationIdle
	dw Porygon2AnimationIdle
	dw PorygonZAnimationIdle
	dw MeowthAnimationIdle
	dw PersianAnimationIdle
	dw TogepiAnimationIdle
	dw TogeticAnimationIdle
	dw TogekissAnimationIdle
	dw RotomAnimationIdle
	dw ChinglingAnimationIdle
	dw ChimechoAnimationIdle
	dw EspurrAnimationIdle
	dw Meowstic_MAnimationIdle
	dw TimburrAnimationIdle
	dw GurdurrAnimationIdle
	dw ConkeldurrAnimationIdle
	dw DittoAnimationIdle
	dw PurrloinAnimationIdle
	dw LiepardAnimationIdle
	dw VulpixAnimationIdle
	dw MukAnimationIdle
	dw Nidoran_MAnimationIdle
	dw NidorinoAnimationIdle
	dw NidorinaAnimationIdle
	dw NidokingAnimationIdle
	dw NidoqueenAnimationIdle
	dw SeviperAnimationIdle
	dw ZangooseAnimationIdle
	dw SentretAnimationIdle
	dw FurretAnimationIdle
	dw SwabluAnimationIdle
	dw AltariaAnimationIdle
	dw MienfooAnimationIdle
	dw MienshaoAnimationIdle
	dw HawluchaAnimationIdle
	dw MareepAnimationIdle
	dw FlaaffyAnimationIdle
	dw AmpharosAnimationIdle
	dw ShinxAnimationIdle
	dw LuxioAnimationIdle
	dw LuxrayAnimationIdle
	dw SandshrewAnimationIdle
	dw SandslashAnimationIdle
	dw PoliwhirlAnimationIdle
	dw PoliwrathAnimationIdle
	dw AbraAnimationIdle
	dw KadabraAnimationIdle
	dw AlakazamAnimationIdle
	dw MachopAnimationIdle
	dw MachokeAnimationIdle
	dw MachampAnimationIdle
	dw BellsproutAnimationIdle
	dw WeepinbellAnimationIdle
	dw VictreebelAnimationIdle
	dw TentacoolAnimationIdle
	dw TentacruelAnimationIdle
	dw GeodudeAnimationIdle
	dw GravelerAnimationIdle
	dw GolemAnimationIdle
	dw PonytaAnimationIdle
	dw RapidashAnimationIdle
	dw SlowpokeAnimationIdle
	dw SlowbroAnimationIdle
	dw Placeholder1AnimationIdle
	dw MagnetonAnimationIdle
	dw FarfetchDAnimationIdle
	dw DoduoAnimationIdle
	dw DodrioAnimationIdle
	dw SeelAnimationIdle
	dw DewgongAnimationIdle
	dw GrimerAnimationIdle
	dw MukAnimationIdle
	dw ShellderAnimationIdle
	dw CloysterAnimationIdle
	dw GastlyAnimationIdle
	dw HaunterAnimationIdle
	dw GengarAnimationIdle
	dw OnixAnimationIdle
	dw DrowzeeAnimationIdle
	dw HypnoAnimationIdle
	dw KrabbyAnimationIdle
	dw KinglerAnimationIdle
	dw VoltorbAnimationIdle
	dw ElectrodeAnimationIdle
	dw ExeggcuteAnimationIdle
	dw ExeggutorAnimationIdle
	dw CuboneAnimationIdle
	dw MarowakAnimationIdle
	dw HitmonleeAnimationIdle
	dw HitmonchanAnimationIdle
	dw LickitungAnimationIdle
	dw KoffingAnimationIdle
	dw WeezingAnimationIdle
	dw RhyhornAnimationIdle
	dw RhydonAnimationIdle
	dw ChanseyAnimationIdle
	dw TangelaAnimationIdle
	dw KangaskhanAnimationIdle
	dw HorseaAnimationIdle
	dw SeadraAnimationIdle
	dw GoldeenAnimationIdle
	dw SeakingAnimationIdle
	dw StaryuAnimationIdle
	dw StarmieAnimationIdle
	dw MrMimeAnimationIdle
	dw ScytherAnimationIdle
	dw JynxAnimationIdle
	dw ElectabuzzAnimationIdle
	dw MagmarAnimationIdle
	dw PinsirAnimationIdle
	dw TaurosAnimationIdle
	dw MagikarpAnimationIdle
	dw GyaradosAnimationIdle
	dw LaprasAnimationIdle
	dw DewpiderAnimationIdle
	dw EeveexAnimationIdle
	dw VaporeonxAnimationIdle
	dw JolteonxAnimationIdle
	dw FlareonxAnimationIdle
	dw Place3AnimationIdle
	dw OmanyteAnimationIdle
	dw OmastarAnimationIdle
	dw KabutoAnimationIdle
	dw KabutopsAnimationIdle
	dw AerodactylAnimationIdle
	dw SnorlaxAnimationIdle
	dw DwebbleAnimationIdle
	dw CrustleAnimationIdle
	dw TyrogueAnimationIdle
	dw DratiniAnimationIdle
	dw DragonairAnimationIdle
	dw DragoniteAnimationIdle
	dw RioluAnimationIdle
	dw LucarioAnimationIdle
	dw ChikoritaAnimationIdle
	dw BayleefAnimationIdle
	dw MeganiumAnimationIdle
	dw AbomasnowAnimationIdle
	dw FerroseedAnimationIdle
	dw FerrothornAnimationIdle
	dw TotodileAnimationIdle
	dw CroconawAnimationIdle
	dw FeraligatrAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw NoctowlAnimationIdle
	dw LedybaAnimationIdle
	dw LedianAnimationIdle
	dw SpinarakAnimationIdle
	dw AriadosAnimationIdle
	dw CrobatAnimationIdle
	dw ChinchouAnimationIdle
	dw LanturnAnimationIdle
	dw PichuAnimationIdle
	dw CleffaAnimationIdle
	dw IgglybuffAnimationIdle
	dw HeidreigonAnimationIdle
	dw CyndaquilAnimationIdle
	dw QuilavaAnimationIdle
	dw TyphlosionAnimationIdle
	dw LittenAnimationIdle
	dw TorracatAnimationIdle
	dw IncineroarAnimationIdle
	dw FennekinAnimationIdle
	dw BraixenAnimationIdle
	dw DelphoxAnimationIdle
	dw VulpixAnimationIdle
	dw NinetalesAnimationIdle
	dw HoppipAnimationIdle
	dw SkiploomAnimationIdle
	dw JumpluffAnimationIdle
	dw AipomAnimationIdle
	dw SunkernAnimationIdle
	dw SunfloraAnimationIdle
	dw YanmaAnimationIdle
	dw WooperAnimationIdle
	dw QuagsireAnimationIdle
	dw EspeonxAnimationIdle
	dw UmbreonxAnimationIdle
	dw MurkrowAnimationIdle
	dw SlowkingAnimationIdle
	dw MisdreavusAnimationIdle
	dw CarbinkAnimationIdle
	dw WobbuffetAnimationIdle
	dw GirafarigAnimationIdle
	dw PinecoAnimationIdle
	dw ForretressAnimationIdle
	dw DunsparceAnimationIdle
	dw GligarAnimationIdle
	dw SteelixAnimationIdle
	dw SnubbullAnimationIdle
	dw GranbullAnimationIdle
	dw QwilfishAnimationIdle
	dw ScizorAnimationIdle
	dw UnownAnimationIdle
	dw HeracrossAnimationIdle
	dw SneaselAnimationIdle
	dw TeddiursaAnimationIdle
	dw UrsaringAnimationIdle
	dw SlugmaAnimationIdle
	dw MagcargoAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw GolurkAnimationIdle
	dw BronzorAnimationIdle
	dw BronzongAnimationIdle
	dw HonedgeAnimationIdle
	dw DoubladeAnimationIdle
	dw AegislashAnimationIdle
	dw PawniardAnimationIdle
	dw BisharpAnimationIdle
	dw YamaskAnimationIdle
	dw CofagrigusAnimationIdle
	dw LitwickAnimationIdle
	dw LampentAnimationIdle
	dw ChandelureAnimationIdle
	dw SpiritombAnimationIdle
	dw DuskullAnimationIdle
	dw DusclopsAnimationIdle
	dw DusknoirAnimationIdle
	dw ArticunoAnimationIdle
	dw ZapdosAnimationIdle
	dw MoltresAnimationIdle
	dw SuicuneAnimationIdle
	dw RaikouAnimationIdle
	dw EnteiAnimationIdle
	dw LatiasAnimationIdle
	dw LatiosAnimationIdle
	dw SilvallyAnimationIdle
	dw MagearnaAnimationIdle
	dw ShayminAnimationIdle
	dw CelebiAnimationIdle
	dw ZygardeAnimationIdle
	dw MewAnimationIdle
	dw MewtwoAnimationIdle
