AnimationIdlePointers:
	dw EeveeAnimationIdle
	dw VaporeonAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw LeafeonAnimationIdle
	dw GlaceonAnimationIdle
	dw SylveonAnimationIdle
	dw ZoruaAnimationIdle
	dw ZoroarkAnimationIdle
	dw RockruffAnimationIdle
	dw LycanrocAnimationIdle
	dw MimikyuAnimationIdle
	dw MagnemiteAnimationIdle
	dw MagnetonAnimationIdle
	dw MagnezoneAnimationIdle
	dw PorygonAnimationIdle
	dw Porygon2AnimationIdle
	dw PorygonZAnimationIdle
	dw MeowthAnimationIdle
	dw PersianAnimationIdle
	dw TogepiAnimationIdle
	dw TogeticAnimationIdle
	dw TogekissAnimationIdle
	dw RotomAnimationIdle
	dw ChinglingAnimationIdle
	dw ChimechoAnimationIdle
	dw EspurrAnimationIdle
	dw Meowstic_MAnimationIdle
	dw TimburrAnimationIdle
	dw GurdurrAnimationIdle
	dw ConkeldurrAnimationIdle
	dw DittoAnimationIdle
	dw PurrloinAnimationIdle
	dw LiepardAnimationIdle
	dw VulpixAnimationIdle
	dw MukAnimationIdle
	dw Nidoran_MAnimationIdle
	dw NidorinoAnimationIdle
	dw NidorinaAnimationIdle
	dw NidokingAnimationIdle
	dw NidoqueenAnimationIdle
	dw SeviperAnimationIdle
	dw ZangooseAnimationIdle
	dw SentretAnimationIdle
	dw FurretAnimationIdle
	dw SwabluAnimationIdle
	dw AltariaAnimationIdle
	dw MienfooAnimationIdle
	dw MienshaoAnimationIdle
	dw HawluchaAnimationIdle
	dw MareepAnimationIdle
	dw FlaaffyAnimationIdle
	dw AmpharosAnimationIdle
	dw ShinxAnimationIdle
	dw LuxioAnimationIdle
	dw LuxrayAnimationIdle
	dw SandshrewAnimationIdle
	dw SandslashAnimationIdle
	dw CutieflyAnimationIdle
	dw RibombeeAnimationIdle
	dw FlabebeAnimationIdle
	dw FloetteAnimationIdle
	dw FlorgesAnimationIdle
	dw IgglybuffAnimationIdle
	dw JigglypuffAnimationIdle
	dw WigglytuffAnimationIdle
	dw ChespinAnimationIdle
	dw QuilladinAnimationIdle
	dw ChesnaughtAnimationIdle
	dw DeerlingAnimationIdle
	dw SawsbuckAnimationIdle
	dw CottoneeAnimationIdle
	dw WhimsicottAnimationIdle
	dw FoongusAnimationIdle
	dw AmoongusAnimationIdle
	dw PhantumpAnimationIdle
	dw TrevanantAnimationIdle
	dw BonslyAnimationIdle
	dw SudowoodoAnimationIdle
	dw PassimianAnimationIdle
	dw StuffulAnimationIdle
	dw BewearAnimationIdle
	dw GirafarigAnimationIdle
	dw HeracrossAnimationIdle
	dw LedybaAnimationIdle
	dw LedianAnimationIdle
	dw JoltikAnimationIdle
	dw GalvantulaAnimationIdle
	dw PinecoAnimationIdle
	dw ForretressAnimationIdle
	dw HaunterAnimationIdle
	dw GengarAnimationIdle
	dw OnixAnimationIdle
	dw DrowzeeAnimationIdle
	dw HypnoAnimationIdle
	dw KrabbyAnimationIdle
	dw KinglerAnimationIdle
	dw VoltorbAnimationIdle
	dw ElectrodeAnimationIdle
	dw ExeggcuteAnimationIdle
	dw ExeggutorAnimationIdle
	dw CuboneAnimationIdle
	dw MarowakAnimationIdle
	dw HitmonleeAnimationIdle
	dw HitmonchanAnimationIdle
	dw LickitungAnimationIdle
	dw KoffingAnimationIdle
	dw WeezingAnimationIdle
	dw RhyhornAnimationIdle
	dw RhydonAnimationIdle
	dw ChanseyAnimationIdle
	dw TangelaAnimationIdle
	dw KangaskhanAnimationIdle
	dw HorseaAnimationIdle
	dw SeadraAnimationIdle
	dw GoldeenAnimationIdle
	dw SeakingAnimationIdle
	dw StaryuAnimationIdle
	dw StarmieAnimationIdle
	dw MrMimeAnimationIdle
	dw ScytherAnimationIdle
	dw JynxAnimationIdle
	dw ElectabuzzAnimationIdle
	dw MagmarAnimationIdle
	dw PinsirAnimationIdle
	dw AzumarillAnimationIdle
	dw MagikarpAnimationIdle
	dw AnorithAnimationIdle
	dw ArmaldoAnimationIdle
	dw DewpiderAnimationIdle
	dw AraquanidAnimationIdle
	dw VaporeonxAnimationIdle
	dw JolteonxAnimationIdle
	dw FlareonxAnimationIdle
	dw Place3AnimationIdle
	dw OmanyteAnimationIdle
	dw OmastarAnimationIdle
	dw KabutoAnimationIdle
	dw KabutopsAnimationIdle
	dw AerodactylAnimationIdle
	dw SnorlaxAnimationIdle
	dw DwebbleAnimationIdle
	dw CrustleAnimationIdle
	dw TyrogueAnimationIdle
	dw DratiniAnimationIdle
	dw DragonairAnimationIdle
	dw DragoniteAnimationIdle
	dw RioluAnimationIdle
	dw LucarioAnimationIdle
	dw ChikoritaAnimationIdle
	dw BayleefAnimationIdle
	dw MeganiumAnimationIdle
	dw AbomasnowAnimationIdle
	dw FerroseedAnimationIdle
	dw FerrothornAnimationIdle
	dw TotodileAnimationIdle
	dw CroconawAnimationIdle
	dw FeraligatrAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw NoctowlAnimationIdle
	dw NoivernAnimationIdle
	dw DruddigonAnimationIdle
	dw AxewAnimationIdle
	dw FraxureAnimationIdle
	dw HaxorusAnimationIdle
	dw Jangmo_oAnimationIdle
	dw Hakamo_oAnimationIdle
	dw Kommo_oAnimationIdle
	dw DeinoAnimationIdle
	dw ZweilousAnimationIdle
	dw HeidreigonAnimationIdle
	dw CyndaquilAnimationIdle
	dw QuilavaAnimationIdle
	dw TyphlosionAnimationIdle
	dw LittenAnimationIdle
	dw TorracatAnimationIdle
	dw IncineroarAnimationIdle
	dw FennekinAnimationIdle
	dw BraixenAnimationIdle
	dw DelphoxAnimationIdle
	dw VulpixAnimationIdle
	dw NinetalesAnimationIdle
	dw SlugmaAnimationIdle
	dw MagcargoAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw FletchlingAnimationIdle
	dw FletchinderAnimationIdle
	dw TalonflameAnimationIdle
	dw HeatmorAnimationIdle
	dw DurantAnimationIdle
	dw ArchenAnimationIdle
	dw ArcheopsAnimationIdle
	dw RoggenrolaAnimationIdle
	dw BoldoreAnimationIdle
	dw GigalithAnimationIdle
	dw CarbinkAnimationIdle
	dw AmauraAnimationIdle
	dw AurorusAnimationIdle
	dw SneaselAnimationIdle
	dw WeavileAnimationIdle
	dw CryogonalAnimationIdle
	dw SnowruntAnimationIdle
	dw GlalieAnimationIdle
	dw FrosslassAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw MamoswineAnimationIdle
	dw UnownAnimationIdle
	dw NatuAnimationIdle
	dw XatuAnimationIdle
	dw SigilyphAnimationIdle
	dw DrillburAnimationIdle
	dw ExcadrillAnimationIdle
	dw BaltoyAnimationIdle
	dw ClaydolAnimationIdle
	dw GolettAnimationIdle
	dw GolurkAnimationIdle
	dw BronzorAnimationIdle
	dw BronzongAnimationIdle
	dw HonedgeAnimationIdle
	dw DoubladeAnimationIdle
	dw AegislashAnimationIdle
	dw PawniardAnimationIdle
	dw BisharpAnimationIdle
	dw YamaskAnimationIdle
	dw CofagrigusAnimationIdle
	dw LitwickAnimationIdle
	dw LampentAnimationIdle
	dw ChandelureAnimationIdle
	dw SpiritombAnimationIdle
	dw DuskullAnimationIdle
	dw DusclopsAnimationIdle
	dw DusknoirAnimationIdle
	dw ArticunoAnimationIdle
	dw ZapdosAnimationIdle
	dw MoltresAnimationIdle
	dw SuicuneAnimationIdle
	dw RaikouAnimationIdle
	dw EnteiAnimationIdle
	dw LatiasAnimationIdle
	dw LatiosAnimationIdle
	dw SilvallyAnimationIdle
	dw MagearnaAnimationIdle
	dw ShayminAnimationIdle
	dw CelebiAnimationIdle
	dw ZygardeAnimationIdle
	dw MewAnimationIdle
	dw MewtwoAnimationIdle
