INCLUDE "constants.asm"


; PokemonPicPointers and UnownPicPointers are assumed to start at the same
; address, but in different banks. This is enforced in pokecrystal.link.


SECTION "Pic Pointers", ROMX

INCLUDE "data/pokemon/pic_pointers.asm"


SECTION "Unown Pic Pointers", ROMX

INCLUDE "data/pokemon/alt_form_pic_pointers.asm"


SECTION "Trainer Pic Pointers", ROMX

INCLUDE "data/trainers/pic_pointers.asm"

SECTION "Portrait Pic Pointers", ROMX

INCLUDE "data/portraits/portrait_pointers.asm"


SECTION "Pics 1", ROMX

CelebiFrontpic:        INCBIN "gfx/pokemon/celebi/front.animated.2bpp.lz"
WigglytuffFrontpic:     INCBIN "gfx/pokemon/wigglytuff/front.animated.2bpp.lz"
FeraligatrFrontpic:  INCBIN "gfx/pokemon/feraligatr/front.animated.2bpp.lz"
DittoFrontpic:    INCBIN "gfx/pokemon/ditto/front.animated.2bpp.lz"
RaikouFrontpic:      INCBIN "gfx/pokemon/raikou/front.animated.2bpp.lz"
ShayminFrontpic:       INCBIN "gfx/pokemon/shaymin/front.animated.2bpp.lz"
DwebbleFrontpic:    INCBIN "gfx/pokemon/dwebble/front.animated.2bpp.lz"
TaurosFrontpic:      INCBIN "gfx/pokemon/tauros/front.animated.2bpp.lz"
JolteonFrontpic:    INCBIN "gfx/pokemon/jolteon/front.animated.2bpp.lz"
EnteiFrontpic:       INCBIN "gfx/pokemon/entei/front.animated.2bpp.lz"
LatiasFrontpic:     INCBIN "gfx/pokemon/latias/front.animated.2bpp.lz"
FerrothornFrontpic:  INCBIN "gfx/pokemon/ferrothorn/front.animated.2bpp.lz"


SECTION "Pics 2", ROMX

SylveonFrontpic:   INCBIN "gfx/pokemon/sylveon/front.animated.2bpp.lz"
RapidashFrontpic:    INCBIN "gfx/pokemon/rapidash/front.animated.2bpp.lz"
MeganiumFrontpic:    INCBIN "gfx/pokemon/meganium/front.animated.2bpp.lz"
TimburrFrontpic:   INCBIN "gfx/pokemon/timburr/front.animated.2bpp.lz"
HitmonleeFrontpic:   INCBIN "gfx/pokemon/hitmonlee/front.animated.2bpp.lz"
ScizorFrontpic:      INCBIN "gfx/pokemon/scizor/front.animated.2bpp.lz"
MagnemiteFrontpic:    INCBIN "gfx/pokemon/magnemite/front.animated.2bpp.lz"
SandshrewFrontpic:    INCBIN "gfx/pokemon/sandshrew/front.animated.2bpp.lz"
MagearnaFrontpic:   INCBIN "gfx/pokemon/magearna/front.animated.2bpp.lz"
TyrogueFrontpic:     INCBIN "gfx/pokemon/tyrogue/front.animated.2bpp.lz"
CrustleFrontpic:      INCBIN "gfx/pokemon/crustle/front.animated.2bpp.lz"
TogeticFrontpic:       INCBIN "gfx/pokemon/togetic/front.animated.2bpp.lz"
RioluFrontpic:      INCBIN "gfx/pokemon/riolu/front.animated.2bpp.lz"
PersianFrontpic:      INCBIN "gfx/pokemon/persian/front.animated.2bpp.lz"
UmbreonFrontpic:   INCBIN "gfx/pokemon/umbreon/front.animated.2bpp.lz"
FerroseedFrontpic:     INCBIN "gfx/pokemon/ferroseed/front.animated.2bpp.lz"


SECTION "Pics 3", ROMX

SteelixFrontpic:     INCBIN "gfx/pokemon/steelix/front.animated.2bpp.lz"
FlorgesFrontpic:    INCBIN "gfx/pokemon/florges/front.animated.2bpp.lz"
GyaradosFrontpic:    INCBIN "gfx/pokemon/gyarados/front.animated.2bpp.lz"
KangaskhanFrontpic:  INCBIN "gfx/pokemon/kangaskhan/front.animated.2bpp.lz"
RhydonFrontpic:      INCBIN "gfx/pokemon/rhydon/front.animated.2bpp.lz"
AmpharosFrontpic:     INCBIN "gfx/pokemon/ampharos/front.animated.2bpp.lz"
RhyhornFrontpic:     INCBIN "gfx/pokemon/rhyhorn/front.animated.2bpp.lz"
PorygonFrontpic:     INCBIN "gfx/pokemon/porygon/front.animated.2bpp.lz"
SlowbroFrontpic:     INCBIN "gfx/pokemon/slowbro/front.animated.2bpp.lz"
RockruffFrontpic:  INCBIN "gfx/pokemon/rockruff/front.animated.2bpp.lz"
WeezingFrontpic:     INCBIN "gfx/pokemon/weezing/front.animated.2bpp.lz"
CloysterFrontpic:    INCBIN "gfx/pokemon/cloyster/front.animated.2bpp.lz"
AegislashFrontpic:    INCBIN "gfx/pokemon/aegislash/front.animated.2bpp.lz"
DewgongFrontpic:     INCBIN "gfx/pokemon/dewgong/front.animated.2bpp.lz"
ChesnaughtFrontpic:  INCBIN "gfx/pokemon/chesnaught/front.animated.2bpp.lz"
RotomFrontpic:      INCBIN "gfx/pokemon/rotom/front.animated.2bpp.lz"
LuxioFrontpic:    INCBIN "gfx/pokemon/luxio/front.animated.2bpp.lz"
OmastarBackpic:      INCBIN "gfx/pokemon/omastar/back.2bpp.lz"


SECTION "Pics 4", ROMX

DodrioFrontpic:      INCBIN "gfx/pokemon/dodrio/front.animated.2bpp.lz"
SlowkingFrontpic:    INCBIN "gfx/pokemon/slowking/front.animated.2bpp.lz"
DusclopsFrontpic:   INCBIN "gfx/pokemon/dusclops/front.animated.2bpp.lz"
OnixFrontpic:        INCBIN "gfx/pokemon/onix/front.animated.2bpp.lz"
SuicuneFrontpic:     INCBIN "gfx/pokemon/suicune/front.animated.2bpp.lz"
JigglypuffFrontpic:     INCBIN "gfx/pokemon/jigglypuff/front.animated.2bpp.lz"
DragoniteFrontpic:   INCBIN "gfx/pokemon/dragonite/front.animated.2bpp.lz"
RibombeeFrontpic:   INCBIN "gfx/pokemon/ribombee/front.animated.2bpp.lz"
ScytherFrontpic:     INCBIN "gfx/pokemon/scyther/front.animated.2bpp.lz"
AerodactylFrontpic:  INCBIN "gfx/pokemon/aerodactyl/front.animated.2bpp.lz"
SeakingFrontpic:     INCBIN "gfx/pokemon/seaking/front.animated.2bpp.lz"
MukFrontpic:         INCBIN "gfx/pokemon/muk/front.animated.2bpp.lz"
CroconawFrontpic:    INCBIN "gfx/pokemon/croconaw/front.animated.2bpp.lz"
HypnoFrontpic:       INCBIN "gfx/pokemon/hypno/front.animated.2bpp.lz"
ConkeldurrFrontpic:    INCBIN "gfx/pokemon/conkeldurr/front.animated.2bpp.lz"
ChimechoFrontpic:   INCBIN "gfx/pokemon/chimecho/front.animated.2bpp.lz"
JolteonxFrontpic:     INCBIN "gfx/pokemon/jolteon/front.animated.2bpp.lz"
LitwickFrontpic:     INCBIN "gfx/pokemon/litwick/front.animated.2bpp.lz"
PinsirFrontpic:      INCBIN "gfx/pokemon/pinsir/front.animated.2bpp.lz"
UnownEFrontpic:      INCBIN "gfx/pokemon/unown_e/front.animated.2bpp.lz"


SECTION "Pics 5", ROMX

NidokingFrontpic:      INCBIN "gfx/pokemon/nidoking/front.animated.2bpp.lz"
KinglerFrontpic:     INCBIN "gfx/pokemon/kingler/front.animated.2bpp.lz"
ExeggcuteFrontpic:   INCBIN "gfx/pokemon/exeggcute/front.animated.2bpp.lz"
BaltoyFrontpic:    INCBIN "gfx/pokemon/baltoy/front.animated.2bpp.lz"
MareepFrontpic:     INCBIN "gfx/pokemon/mareep/front.animated.2bpp.lz"
ChandelureFrontpic:    INCBIN "gfx/pokemon/chandelure/front.animated.2bpp.lz"
PorygonZFrontpic:    INCBIN "gfx/pokemon/porygonz/front.animated.2bpp.lz"
AltariaFrontpic:    INCBIN "gfx/pokemon/altaria/front.animated.2bpp.lz"
ElectabuzzFrontpic:  INCBIN "gfx/pokemon/electabuzz/front.animated.2bpp.lz"
DoubladeFrontpic:     INCBIN "gfx/pokemon/doublade/front.animated.2bpp.lz"
LickitungFrontpic:   INCBIN "gfx/pokemon/lickitung/front.animated.2bpp.lz"
YamaskFrontpic:     INCBIN "gfx/pokemon/yamask/front.animated.2bpp.lz"
EspeonFrontpic:  INCBIN "gfx/pokemon/espeon/front.animated.2bpp.lz"
FloetteFrontpic:     INCBIN "gfx/pokemon/floette/front.animated.2bpp.lz"
ExeggutorFrontpic:   INCBIN "gfx/pokemon/exeggutor/front.animated.2bpp.lz"
GastlyFrontpic:      INCBIN "gfx/pokemon/gastly/front.animated.2bpp.lz"
DelphoxFrontpic:   INCBIN "gfx/pokemon/delphox/front.animated.2bpp.lz"
FurretFrontpic:    INCBIN "gfx/pokemon/furret/front.animated.2bpp.lz"
MrMimeFrontpic:      INCBIN "gfx/pokemon/mr__mime/front.animated.2bpp.lz"
NatuFrontpic:   INCBIN "gfx/pokemon/natu/front.animated.2bpp.lz"


SECTION "Pics 6", ROMX

AriadosFrontpic:     INCBIN "gfx/pokemon/ariados/front.animated.2bpp.lz"
NoctowlFrontpic:     INCBIN "gfx/pokemon/noctowl/front.animated.2bpp.lz"
GlaceonFrontpic:   INCBIN "gfx/pokemon/glaceon/front.animated.2bpp.lz"
LaprasFrontpic:      INCBIN "gfx/pokemon/lapras/front.animated.2bpp.lz"
GolemFrontpic:       INCBIN "gfx/pokemon/golem/front.animated.2bpp.lz"
CutieflyFrontpic:   INCBIN "gfx/pokemon/cutiefly/front.animated.2bpp.lz"
DrillburFrontpic:    INCBIN "gfx/pokemon/drillbur/front.animated.2bpp.lz"
BisharpFrontpic:    INCBIN "gfx/pokemon/bisharp/front.animated.2bpp.lz"
KabutopsFrontpic:    INCBIN "gfx/pokemon/kabutops/front.animated.2bpp.lz"
IncineroarFrontpic:    INCBIN "gfx/pokemon/incineroar/front.animated.2bpp.lz"
Meowstic_MFrontpic:    INCBIN "gfx/pokemon/meowstic_m/front.animated.2bpp.lz"
FlareonFrontpic:     INCBIN "gfx/pokemon/flareon/front.animated.2bpp.lz"
FarfetchDFrontpic:   INCBIN "gfx/pokemon/farfetch_d/front.animated.2bpp.lz"
ZangooseFrontpic:   INCBIN "gfx/pokemon/zangoose/front.animated.2bpp.lz"
BayleefFrontpic:     INCBIN "gfx/pokemon/bayleef/front.animated.2bpp.lz"
MagmarFrontpic:      INCBIN "gfx/pokemon/magmar/front.animated.2bpp.lz"
SawsbuckFrontpic:  INCBIN "gfx/pokemon/sawsbuck/front.animated.2bpp.lz"
ArticunoFrontpic:      INCBIN "gfx/pokemon/articuno/front.animated.2bpp.lz"
JumpluffFrontpic:    INCBIN "gfx/pokemon/jumpluff/front.animated.2bpp.lz"
MarowakFrontpic:     INCBIN "gfx/pokemon/marowak/front.animated.2bpp.lz"
GligarFrontpic:      INCBIN "gfx/pokemon/gligar/front.animated.2bpp.lz"
DunsparceFrontpic:   INCBIN "gfx/pokemon/dunsparce/front.animated.2bpp.lz"


SECTION "Pics 7", ROMX

VaporeonFrontpic:    INCBIN "gfx/pokemon/vaporeon/front.animated.2bpp.lz"
GirafarigFrontpic:   INCBIN "gfx/pokemon/girafarig/front.animated.2bpp.lz"
DrowzeeFrontpic:     INCBIN "gfx/pokemon/drowzee/front.animated.2bpp.lz"
XatuFrontpic:     INCBIN "gfx/pokemon/xatu/front.animated.2bpp.lz"
FennekinFrontpic:   INCBIN "gfx/pokemon/fennekin/front.animated.2bpp.lz"
SnorlaxFrontpic:     INCBIN "gfx/pokemon/snorlax/front.animated.2bpp.lz"
NidorinoFrontpic:  INCBIN "gfx/pokemon/nidorino/front.animated.2bpp.lz"
YanmaFrontpic:       INCBIN "gfx/pokemon/yanma/front.animated.2bpp.lz"
SpiritombFrontpic:    INCBIN "gfx/pokemon/spiritomb/front.animated.2bpp.lz"
LiepardFrontpic:    INCBIN "gfx/pokemon/liepard/front.animated.2bpp.lz"
PonytaFrontpic:      INCBIN "gfx/pokemon/ponyta/front.animated.2bpp.lz"
MurkrowFrontpic:     INCBIN "gfx/pokemon/murkrow/front.animated.2bpp.lz"
GravelerFrontpic:    INCBIN "gfx/pokemon/graveler/front.animated.2bpp.lz"
StarmieFrontpic:     INCBIN "gfx/pokemon/starmie/front.animated.2bpp.lz"
MagnezoneFrontpic:   INCBIN "gfx/pokemon/magnezone/front.animated.2bpp.lz"
LedybaFrontpic:      INCBIN "gfx/pokemon/ledyba/front.animated.2bpp.lz"
GengarFrontpic:      INCBIN "gfx/pokemon/gengar/front.animated.2bpp.lz"
OmastarFrontpic:     INCBIN "gfx/pokemon/omastar/front.animated.2bpp.lz"
GolettFrontpic:   INCBIN "gfx/pokemon/golett/front.animated.2bpp.lz"
MienshaoFrontpic:     INCBIN "gfx/pokemon/mienshao/front.animated.2bpp.lz"
MagnetonFrontpic:    INCBIN "gfx/pokemon/placeholder2/front.animated.2bpp.lz"
DragonairFrontpic:   INCBIN "gfx/pokemon/dragonair/front.animated.2bpp.lz"
ForretressFrontpic:  INCBIN "gfx/pokemon/forretress/front.animated.2bpp.lz"
CyndaquilFrontpic:     INCBIN "gfx/pokemon/cyndaquil/front.animated.2bpp.lz"
KangaskhanBackpic:   INCBIN "gfx/pokemon/kangaskhan/back.2bpp.lz"


SECTION "Pics 8", ROMX

SeelFrontpic:        INCBIN "gfx/pokemon/seel/front.animated.2bpp.lz"
CrobatFrontpic:      INCBIN "gfx/pokemon/crobat/front.animated.2bpp.lz"
ChanseyFrontpic:     INCBIN "gfx/pokemon/chansey/front.animated.2bpp.lz"
TangelaFrontpic:     INCBIN "gfx/pokemon/tangela/front.animated.2bpp.lz"
SnubbullFrontpic:    INCBIN "gfx/pokemon/snubbull/front.animated.2bpp.lz"
GranbullFrontpic:    INCBIN "gfx/pokemon/granbull/front.animated.2bpp.lz"
MoltresFrontpic:     INCBIN "gfx/pokemon/moltres/front.animated.2bpp.lz"
HaunterFrontpic:     INCBIN "gfx/pokemon/haunter/front.animated.2bpp.lz"
SunfloraFrontpic:    INCBIN "gfx/pokemon/sunflora/front.animated.2bpp.lz"
UmbreonxFrontpic:     INCBIN "gfx/pokemon/umbreon/front.animated.2bpp.lz"
ChikoritaFrontpic:   INCBIN "gfx/pokemon/chikorita/front.animated.2bpp.lz"
GoldeenFrontpic:     INCBIN "gfx/pokemon/goldeen/front.animated.2bpp.lz"
EspeonxFrontpic:      INCBIN "gfx/pokemon/espeon/front.animated.2bpp.lz"
TyphlosionFrontpic:        INCBIN "gfx/pokemon/typhlosion/front.animated.2bpp.lz"
LucarioFrontpic:         INCBIN "gfx/pokemon/lucario/front.animated.2bpp.lz"
BronzongFrontpic:   INCBIN "gfx/pokemon/bronzong/front.animated.2bpp.lz"
JynxFrontpic:        INCBIN "gfx/pokemon/jynx/front.animated.2bpp.lz"
WobbuffetFrontpic:   INCBIN "gfx/pokemon/wobbuffet/front.animated.2bpp.lz"
HonedgeFrontpic:    INCBIN "gfx/pokemon/honedge/front.animated.2bpp.lz"
LedianFrontpic:      INCBIN "gfx/pokemon/ledian/front.animated.2bpp.lz"
SeviperFrontpic:       INCBIN "gfx/pokemon/seviper/front.animated.2bpp.lz"
TorracatFrontpic:     INCBIN "gfx/pokemon/torracat/front.animated.2bpp.lz"
VaporeonxFrontpic:     INCBIN "gfx/pokemon/vaporeon/front.animated.2bpp.lz"
PupitarFrontpic:      INCBIN "gfx/pokemon/pupitar/front.animated.2bpp.lz"
AbomasnowFrontpic:   INCBIN "gfx/pokemon/abomasnow/front.animated.2bpp.lz"
HitmonchanFrontpic:  INCBIN "gfx/pokemon/hitmonchan/front.animated.2bpp.lz"


SECTION "Pics 9", ROMX

QuagsireFrontpic:    INCBIN "gfx/pokemon/quagsire/front.animated.2bpp.lz"
TogepiFrontpic:       INCBIN "gfx/pokemon/togepi/front.animated.2bpp.lz"
TogekissFrontpic:     INCBIN "gfx/pokemon/togekiss/front.animated.2bpp.lz"
SeadraFrontpic:      INCBIN "gfx/pokemon/seadra/front.animated.2bpp.lz"
ZapdosFrontpic:       INCBIN "gfx/pokemon/magby/front.animated.2bpp.lz"
QuilladinFrontpic:  INCBIN "gfx/pokemon/quilladin/front.animated.2bpp.lz"
TotodileFrontpic:    INCBIN "gfx/pokemon/totodile/front.animated.2bpp.lz"
GolurkFrontpic:     INCBIN "gfx/pokemon/golurk/front.animated.2bpp.lz"
FirebreatherPic:     INCBIN "gfx/trainers/firebreather.2bpp.lz"
IgglybuffFrontpic:      INCBIN "gfx/pokemon/igglybuff/front.animated.2bpp.lz"
ChinchouFrontpic:    INCBIN "gfx/pokemon/chinchou/front.animated.2bpp.lz"
Porygon2Frontpic:     INCBIN "gfx/pokemon/porygon2/front.animated.2bpp.lz"
ChampionPic:         INCBIN "gfx/trainers/champion.2bpp.lz"
MeowthFrontpic:     INCBIN "gfx/pokemon/meowth/front.animated.2bpp.lz"
MagikarpFrontpic:    INCBIN "gfx/pokemon/magikarp/front.animated.2bpp.lz"
FlareonxFrontpic:  INCBIN "gfx/pokemon/flareon/front.animated.2bpp.lz"
CuboneFrontpic:      INCBIN "gfx/pokemon/cubone/front.animated.2bpp.lz"
BlackbeltTPic:       INCBIN "gfx/trainers/blackbelt_t.2bpp.lz"
BikerPic:            INCBIN "gfx/trainers/biker.2bpp.lz"
GurdurrFrontpic:    INCBIN "gfx/pokemon/gurdurr/front.animated.2bpp.lz"
Place3Frontpic:     INCBIN "gfx/pokemon/place3/front.animated.2bpp.lz"
BrunoPic:            INCBIN "gfx/trainers/bruno.2bpp.lz"
GrimerFrontpic:      INCBIN "gfx/pokemon/grimer/front.animated.2bpp.lz"
StaryuFrontpic:      INCBIN "gfx/pokemon/staryu/front.animated.2bpp.lz"
HikerPic:            INCBIN "gfx/trainers/hiker.2bpp.lz"
HawluchaFrontpic:      INCBIN "gfx/pokemon/hawlucha/front.animated.2bpp.lz"
LampentFrontpic:    INCBIN "gfx/pokemon/lampent/front.animated.2bpp.lz"
ChinglingFrontpic:   INCBIN "gfx/pokemon/chingling/front.animated.2bpp.lz"
EspurrFrontpic:    INCBIN "gfx/pokemon/espurr/front.animated.2bpp.lz"


SECTION "Pics 10", ROMX

MagnetonFrontpic:      INCBIN "gfx/pokemon/magneton/front.animated.2bpp.lz"
FurretBackpic:     INCBIN "gfx/pokemon/furret/back.2bpp.lz"
MisdreavusFrontpic:  INCBIN "gfx/pokemon/misdreavus/front.animated.2bpp.lz"
ShinxFrontpic:      INCBIN "gfx/pokemon/shinx/front.animated.2bpp.lz"
PawniardFrontpic:    INCBIN "gfx/pokemon/pawniard/front.animated.2bpp.lz"
ZygardeFrontpic:      INCBIN "gfx/pokemon/zygarde/front.animated.2bpp.lz"
MediumPic:           INCBIN "gfx/trainers/medium.2bpp.lz"
PinecoFrontpic:      INCBIN "gfx/pokemon/pineco/front.animated.2bpp.lz"
KrabbyFrontpic:      INCBIN "gfx/pokemon/krabby/front.animated.2bpp.lz"
FisherPic:           INCBIN "gfx/trainers/fisher.2bpp.lz"
Nidoran_MFrontpic:  INCBIN "gfx/pokemon/nidoran_m/front.animated.2bpp.lz"
SentretFrontpic:       INCBIN "gfx/pokemon/sentret/front.animated.2bpp.lz"
DittoBackpic:     INCBIN "gfx/pokemon/ditto/back.2bpp.lz"
PokefanmPic:         INCBIN "gfx/trainers/pokefan_m.2bpp.lz"
BoarderPic:          INCBIN "gfx/trainers/boarder.2bpp.lz"
FlaaffyFrontpic:     INCBIN "gfx/pokemon/flaaffy/front.animated.2bpp.lz"
LeafeonFrontpic:    INCBIN "gfx/pokemon/leafeon/front.animated.2bpp.lz"
WigglytuffBackpic:      INCBIN "gfx/pokemon/wigglytuff/back.2bpp.lz"
KoffingFrontpic:     INCBIN "gfx/pokemon/koffing/front.animated.2bpp.lz"
SwabluFrontpic:     INCBIN "gfx/pokemon/swablu/front.animated.2bpp.lz"
ExeggutorBackpic:    INCBIN "gfx/pokemon/exeggutor/back.2bpp.lz"
LanturnFrontpic:     INCBIN "gfx/pokemon/lanturn/front.animated.2bpp.lz"
DuskullFrontpic:     INCBIN "gfx/pokemon/duskull/front.animated.2bpp.lz"
SkiploomFrontpic:    INCBIN "gfx/pokemon/skiploom/front.animated.2bpp.lz"
LittenFrontpic:      INCBIN "gfx/pokemon/litten/front.animated.2bpp.lz"
ChuckPic:            INCBIN "gfx/trainers/chuck.2bpp.lz"
EeveeFrontpic:       INCBIN "gfx/pokemon/eevee/front.animated.2bpp.lz"
RockruffBackpic:   INCBIN "gfx/pokemon/rockruff/back.2bpp.lz"
NidorinaFrontpic:       INCBIN "gfx/pokemon/nidorina/front.animated.2bpp.lz"
KimonoGirlPic:       INCBIN "gfx/trainers/kimono_girl.2bpp.lz"
FlorgesBackpic:     INCBIN "gfx/pokemon/florges/back.2bpp.lz"
AipomFrontpic:       INCBIN "gfx/pokemon/aipom/front.animated.2bpp.lz"
FlabebeFrontpic:        INCBIN "gfx/pokemon/flabebe/front.animated.2bpp.lz"
DusclopsBackpic:    INCBIN "gfx/pokemon/dusclops/back.2bpp.lz"
CloysterBackpic:     INCBIN "gfx/pokemon/cloyster/back.2bpp.lz"


SECTION "Pics 11", ROMX

TyranitarFrontpic:    INCBIN "gfx/pokemon/tyranitar/front.animated.2bpp.lz"
UnownFBackpic:       INCBIN "gfx/pokemon/unown_f/back.2bpp.lz"
DodrioBackpic:       INCBIN "gfx/pokemon/dodrio/back.2bpp.lz"
PurrloinFrontpic:    INCBIN "gfx/pokemon/purrloin/front.animated.2bpp.lz"
ExcadrillFrontpic:      INCBIN "gfx/pokemon/excadrill/front.animated.2bpp.lz"
LuxrayFrontpic:   INCBIN "gfx/pokemon/luxray/front.animated.2bpp.lz"
SlowpokeFrontpic:    INCBIN "gfx/pokemon/slowpoke/front.animated.2bpp.lz"
DusknoirFrontpic:    INCBIN "gfx/pokemon/dusknoir/front.animated.2bpp.lz"
JugglerPic:          INCBIN "gfx/trainers/juggler.2bpp.lz"
BraixenFrontpic:      INCBIN "gfx/pokemon/braixen/front.animated.2bpp.lz"
GuitaristPic:        INCBIN "gfx/trainers/guitarist.2bpp.lz"
PokefanfPic:         INCBIN "gfx/trainers/pokefan_f.2bpp.lz"
AltariaBackpic:     INCBIN "gfx/pokemon/altaria/back.2bpp.lz"
ClairPic:            INCBIN "gfx/trainers/clair.2bpp.lz"
PokemaniacPic:       INCBIN "gfx/trainers/pokemaniac.2bpp.lz"
OmanyteFrontpic:     INCBIN "gfx/pokemon/omanyte/front.animated.2bpp.lz"
SkierPic:            INCBIN "gfx/trainers/skier.2bpp.lz"
SilvallyFrontpic:     INCBIN "gfx/pokemon/silvally/front.animated.2bpp.lz"
ChespinFrontpic:  INCBIN "gfx/pokemon/chespin/front.animated.2bpp.lz"
ShellderFrontpic:    INCBIN "gfx/pokemon/shellder/front.animated.2bpp.lz"
DeerlingFrontpic:   INCBIN "gfx/pokemon/deerling/front.animated.2bpp.lz"
CleffaFrontpic:      INCBIN "gfx/pokemon/cleffa/front.animated.2bpp.lz"
GyaradosBackpic:     INCBIN "gfx/pokemon/gyarados/back.2bpp.lz"
YanmaBackpic:        INCBIN "gfx/pokemon/yanma/back.2bpp.lz"
PinsirBackpic:       INCBIN "gfx/pokemon/pinsir/back.2bpp.lz"
LassPic:             INCBIN "gfx/trainers/lass.2bpp.lz"
LiepardBackpic:     INCBIN "gfx/pokemon/liepard/back.2bpp.lz"
DoduoFrontpic:       INCBIN "gfx/pokemon/doduo/front.animated.2bpp.lz"
FeraligatrBackpic:   INCBIN "gfx/pokemon/feraligatr/back.2bpp.lz"
DratiniFrontpic:     INCBIN "gfx/pokemon/dratini/front.animated.2bpp.lz"
MagnetonBackpic:     INCBIN "gfx/pokemon/placeholder2/back.2bpp.lz"
QwilfishFrontpic:    INCBIN "gfx/pokemon/qwilfish/front.animated.2bpp.lz"
LatiasBackpic:      INCBIN "gfx/pokemon/latias/back.2bpp.lz"
SlowkingBackpic:     INCBIN "gfx/pokemon/slowking/back.2bpp.lz"
ArticunoBackpic:       INCBIN "gfx/pokemon/articuno/back.2bpp.lz"
ZygardeBackpic:       INCBIN "gfx/pokemon/zygarde/back.2bpp.lz"
KrabbyBackpic:       INCBIN "gfx/pokemon/krabby/back.2bpp.lz"


SECTION "Pics 12", ROMX

BugCatcherPic:       INCBIN "gfx/trainers/bug_catcher.2bpp.lz"
SnorlaxBackpic:      INCBIN "gfx/pokemon/snorlax/back.2bpp.lz"
JolteonBackpic:     INCBIN "gfx/pokemon/jolteon/back.2bpp.lz"
TyrogueBackpic:      INCBIN "gfx/pokemon/tyrogue/back.2bpp.lz"
SunfloraBackpic:     INCBIN "gfx/pokemon/sunflora/back.2bpp.lz"
CofagrigusFrontpic:      INCBIN "gfx/pokemon/cofagrigus/front.animated.2bpp.lz"
RhydonBackpic:       INCBIN "gfx/pokemon/rhydon/back.2bpp.lz"
LatiosFrontpic:    INCBIN "gfx/pokemon/latios/front.animated.2bpp.lz"
MagearnaBackpic:    INCBIN "gfx/pokemon/magearna/back.2bpp.lz"
ChimechoBackpic:    INCBIN "gfx/pokemon/chimecho/back.2bpp.lz"
SeadraBackpic:       INCBIN "gfx/pokemon/seadra/back.2bpp.lz"
TwinsPic:            INCBIN "gfx/trainers/twins.2bpp.lz"
FarfetchDBackpic:    INCBIN "gfx/pokemon/farfetch_d/back.2bpp.lz"
GurdurrBackpic:     INCBIN "gfx/pokemon/gurdurr/back.2bpp.lz"
LedybaBackpic:       INCBIN "gfx/pokemon/ledyba/back.2bpp.lz"
AbomasnowBackpic:    INCBIN "gfx/pokemon/abomasnow/back.2bpp.lz"
BayleefBackpic:      INCBIN "gfx/pokemon/bayleef/back.2bpp.lz"
NidoqueenFrontpic:      INCBIN "gfx/pokemon/nidoqueen/front.animated.2bpp.lz"
RapidashBackpic:     INCBIN "gfx/pokemon/rapidash/back.2bpp.lz"
DoduoBackpic:        INCBIN "gfx/pokemon/doduo/back.2bpp.lz"
HoppipFrontpic:      INCBIN "gfx/pokemon/hoppip/front.animated.2bpp.lz"
ShinxBackpic:       INCBIN "gfx/pokemon/shinx/back.2bpp.lz"
MagmarBackpic:       INCBIN "gfx/pokemon/magmar/back.2bpp.lz"
HypnoBackpic:        INCBIN "gfx/pokemon/hypno/back.2bpp.lz"
FerroseedBackpic:      INCBIN "gfx/pokemon/ferroseed/back.2bpp.lz"
CroconawBackpic:     INCBIN "gfx/pokemon/croconaw/back.2bpp.lz"
ChinglingBackpic:    INCBIN "gfx/pokemon/chingling/back.2bpp.lz"
SailorPic:           INCBIN "gfx/trainers/sailor.2bpp.lz"
BeautyPic:           INCBIN "gfx/trainers/beauty.2bpp.lz"
ShellderBackpic:     INCBIN "gfx/pokemon/shellder/back.2bpp.lz"
NidorinaBackpic:        INCBIN "gfx/pokemon/nidorina/back.2bpp.lz"
SigilyphFrontpic:   INCBIN "gfx/pokemon/sigilyph/front.animated.2bpp.lz"
CuboneBackpic:       INCBIN "gfx/pokemon/cubone/back.2bpp.lz"
GruntmPic:           INCBIN "gfx/trainers/grunt_m.2bpp.lz"
SeviperBackpic:        INCBIN "gfx/pokemon/seviper/back.2bpp.lz"
BaltoyBackpic:     INCBIN "gfx/pokemon/baltoy/back.2bpp.lz"
KabutopsBackpic:     INCBIN "gfx/pokemon/kabutops/back.2bpp.lz"
MagnemiteBackpic:     INCBIN "gfx/pokemon/magnemite/back.2bpp.lz"
SandshrewBackpic:     INCBIN "gfx/pokemon/sandshrew/back.2bpp.lz"
FlareonBackpic:      INCBIN "gfx/pokemon/flareon/back.2bpp.lz"
GoldeenBackpic:      INCBIN "gfx/pokemon/goldeen/back.2bpp.lz"


SECTION "Pics 13", ROMX

EeveexFrontpic:   INCBIN "gfx/pokemon/eevee/front.animated.2bpp.lz"
StarmieBackpic:      INCBIN "gfx/pokemon/starmie/back.2bpp.lz"
OmanyteBackpic:      INCBIN "gfx/pokemon/omanyte/back.2bpp.lz"
MagnetonBackpic:       INCBIN "gfx/pokemon/magneton/back.2bpp.lz"
ScientistPic:        INCBIN "gfx/trainers/scientist.2bpp.lz"
QwilfishBackpic:     INCBIN "gfx/pokemon/qwilfish/back.2bpp.lz"
GligarBackpic:       INCBIN "gfx/pokemon/gligar/back.2bpp.lz"
FerrothornBackpic:   INCBIN "gfx/pokemon/ferrothorn/back.2bpp.lz"
EspeonBackpic:   INCBIN "gfx/pokemon/espeon/back.2bpp.lz"
TimburrBackpic:    INCBIN "gfx/pokemon/timburr/back.2bpp.lz"
PichuFrontpic:       INCBIN "gfx/pokemon/pichu/front.animated.2bpp.lz"
ElectabuzzBackpic:   INCBIN "gfx/pokemon/electabuzz/back.2bpp.lz"
LedianBackpic:       INCBIN "gfx/pokemon/ledian/back.2bpp.lz"
SilvallyBackpic:      INCBIN "gfx/pokemon/silvally/back.2bpp.lz"
NatuBackpic:    INCBIN "gfx/pokemon/natu/back.2bpp.lz"
UnownDFrontpic:      INCBIN "gfx/pokemon/unown_d/front.animated.2bpp.lz"
MoltresBackpic:      INCBIN "gfx/pokemon/moltres/back.2bpp.lz"
SteelixBackpic:      INCBIN "gfx/pokemon/steelix/back.2bpp.lz"
MareepBackpic:      INCBIN "gfx/pokemon/mareep/back.2bpp.lz"
LtSurgePic:          INCBIN "gfx/trainers/lt_surge.2bpp.lz"
TeacherPic:          INCBIN "gfx/trainers/teacher.2bpp.lz"
EggPic:              INCBIN "gfx/pokemon/egg/front.animated.2bpp.lz"
EeveeBackpic:        INCBIN "gfx/pokemon/eevee/back.2bpp.lz"
UnownFrontpic:     INCBIN "gfx/pokemon/unown/front.animated.2bpp.lz"
PonytaBackpic:       INCBIN "gfx/pokemon/ponyta/back.2bpp.lz"
SandslashFrontpic:     INCBIN "gfx/pokemon/sandslash/front.animated.2bpp.lz"
BronzorFrontpic:    INCBIN "gfx/pokemon/bronzor/front.animated.2bpp.lz"
OnixBackpic:         INCBIN "gfx/pokemon/onix/back.2bpp.lz"
KoffingBackpic:      INCBIN "gfx/pokemon/koffing/back.2bpp.lz"
BirdKeeperPic:       INCBIN "gfx/trainers/bird_keeper.2bpp.lz"
FalknerPic:          INCBIN "gfx/trainers/falkner.2bpp.lz"
KarenPic:            INCBIN "gfx/trainers/karen.2bpp.lz"
Meowstic_MBackpic:     INCBIN "gfx/pokemon/meowstic_m/back.2bpp.lz"
SawsbuckBackpic:   INCBIN "gfx/pokemon/sawsbuck/back.2bpp.lz"
LuxrayBackpic:    INCBIN "gfx/pokemon/luxray/back.2bpp.lz"
KogaPic:             INCBIN "gfx/trainers/koga.2bpp.lz"
JigglypuffBackpic:      INCBIN "gfx/pokemon/jigglypuff/back.2bpp.lz"
RotomBackpic:       INCBIN "gfx/pokemon/rotom/back.2bpp.lz"
RibombeeBackpic:    INCBIN "gfx/pokemon/ribombee/back.2bpp.lz"
SwimmermPic:         INCBIN "gfx/trainers/swimmer_m.2bpp.lz"
SunkernFrontpic:     INCBIN "gfx/pokemon/sunkern/front.animated.2bpp.lz"
ConkeldurrBackpic:     INCBIN "gfx/pokemon/conkeldurr/back.2bpp.lz"
MysticalmanPic:      INCBIN "gfx/trainers/mysticalman.2bpp.lz"


SECTION "Pics 14", ROMX

CooltrainerfPic:     INCBIN "gfx/trainers/cooltrainer_f.2bpp.lz"
ElectrodeFrontpic:   INCBIN "gfx/pokemon/electrode/front.animated.2bpp.lz"
TorracatBackpic:      INCBIN "gfx/pokemon/torracat/back.2bpp.lz"
LarvitarFrontpic:     INCBIN "gfx/pokemon/larvitar/front.animated.2bpp.lz"
CyndaquilBackpic:      INCBIN "gfx/pokemon/cyndaquil/back.2bpp.lz"
BugsyPic:            INCBIN "gfx/trainers/bugsy.2bpp.lz"
MarowakBackpic:      INCBIN "gfx/pokemon/marowak/back.2bpp.lz"
GeodudeBackpic:      INCBIN "gfx/pokemon/geodude/back.2bpp.lz"
ScytherBackpic:      INCBIN "gfx/pokemon/scyther/back.2bpp.lz"
ZangooseBackpic:    INCBIN "gfx/pokemon/zangoose/back.2bpp.lz"
HitmonchanBackpic:   INCBIN "gfx/pokemon/hitmonchan/back.2bpp.lz"
JumpluffBackpic:     INCBIN "gfx/pokemon/jumpluff/back.2bpp.lz"
CooltrainermPic:     INCBIN "gfx/trainers/cooltrainer_m.2bpp.lz"
SylveonBackpic:    INCBIN "gfx/pokemon/sylveon/back.2bpp.lz"
MisdreavusBackpic:   INCBIN "gfx/pokemon/misdreavus/back.2bpp.lz"
DuskullBackpic:      INCBIN "gfx/pokemon/duskull/back.2bpp.lz"
GeodudeFrontpic:     INCBIN "gfx/pokemon/geodude/front.animated.2bpp.lz"
ScizorBackpic:       INCBIN "gfx/pokemon/scizor/back.2bpp.lz"
GirafarigBackpic:    INCBIN "gfx/pokemon/girafarig/back.2bpp.lz"
ChandelureBackpic:     INCBIN "gfx/pokemon/chandelure/back.2bpp.lz"
SpiritombBackpic:     INCBIN "gfx/pokemon/spiritomb/back.2bpp.lz"
UmbreonBackpic:    INCBIN "gfx/pokemon/umbreon/back.2bpp.lz"
FloetteBackpic:      INCBIN "gfx/pokemon/floette/back.2bpp.lz"
LuxioBackpic:     INCBIN "gfx/pokemon/luxio/back.2bpp.lz"
PupitarBackpic:       INCBIN "gfx/pokemon/pupitar/back.2bpp.lz"
GlaceonBackpic:    INCBIN "gfx/pokemon/glaceon/back.2bpp.lz"
ExeggcuteBackpic:    INCBIN "gfx/pokemon/exeggcute/back.2bpp.lz"
ZweilousFrontpic:   INCBIN "gfx/pokemon/zweilous/front.animated.2bpp.lz"
PorygonZBackpic:     INCBIN "gfx/pokemon/porygonz/back.2bpp.lz"
TogepiBackpic:        INCBIN "gfx/pokemon/togepi/back.2bpp.lz"
SeakingBackpic:      INCBIN "gfx/pokemon/seaking/back.2bpp.lz"
BurglarPic:          INCBIN "gfx/trainers/burglar.2bpp.lz"
FlaaffyBackpic:      INCBIN "gfx/pokemon/flaaffy/back.2bpp.lz"
TogekissBackpic:      INCBIN "gfx/pokemon/togekiss/back.2bpp.lz"
KabutoFrontpic:      INCBIN "gfx/pokemon/kabuto/front.animated.2bpp.lz"
LittenBackpic:       INCBIN "gfx/pokemon/litten/back.2bpp.lz"
BronzorBackpic:     INCBIN "gfx/pokemon/bronzor/back.2bpp.lz"
DewpiderFrontpic:       INCBIN "gfx/pokemon/dewpider/front.animated.2bpp.lz"
YamaskBackpic:      INCBIN "gfx/pokemon/yamask/back.2bpp.lz"
CamperPic:           INCBIN "gfx/trainers/camper.2bpp.lz"
WooperFrontpic:      INCBIN "gfx/pokemon/wooper/front.animated.2bpp.lz"
PurrloinBackpic:     INCBIN "gfx/pokemon/purrloin/back.2bpp.lz"
SwabluBackpic:      INCBIN "gfx/pokemon/swablu/back.2bpp.lz"
FennekinBackpic:    INCBIN "gfx/pokemon/fennekin/back.2bpp.lz"


SECTION "Pics 15", ROMX

Rival1Pic:           INCBIN "gfx/trainers/rival1.2bpp.lz"
ClaydolBackpic:       INCBIN "gfx/pokemon/claydol/back.2bpp.lz"
RioluBackpic:       INCBIN "gfx/pokemon/riolu/back.2bpp.lz"
PokemonProfPic:      INCBIN "gfx/trainers/oak.2bpp.lz"
CalPic:              INCBIN "gfx/trainers/cal.2bpp.lz"
SwimmerfPic:         INCBIN "gfx/trainers/swimmer_f.2bpp.lz"
MienfooFrontpic:     INCBIN "gfx/pokemon/mienfoo/front.animated.2bpp.lz"
OfficerPic:          INCBIN "gfx/trainers/officer.2bpp.lz"
MukBackpic:          INCBIN "gfx/pokemon/muk/back.2bpp.lz"
HonedgeBackpic:     INCBIN "gfx/pokemon/honedge/back.2bpp.lz"
SabrinaPic:          INCBIN "gfx/trainers/sabrina.2bpp.lz"
MagikarpBackpic:     INCBIN "gfx/pokemon/magikarp/back.2bpp.lz"
AriadosBackpic:      INCBIN "gfx/pokemon/ariados/back.2bpp.lz"
XatuBackpic:      INCBIN "gfx/pokemon/xatu/back.2bpp.lz"
UmbreonxBackpic:      INCBIN "gfx/pokemon/umbreon/back.2bpp.lz"
MurkrowBackpic:      INCBIN "gfx/pokemon/murkrow/back.2bpp.lz"
VaporeonBackpic:      INCBIN "gfx/pokemon/vaporeon/back.2bpp.lz"
SlowbroBackpic:      INCBIN "gfx/pokemon/slowbro/back.2bpp.lz"
PsychicTPic:         INCBIN "gfx/trainers/psychic_t.2bpp.lz"
AmpharosBackpic:      INCBIN "gfx/pokemon/ampharos/back.2bpp.lz"
WeezingBackpic:      INCBIN "gfx/pokemon/weezing/back.2bpp.lz"
EnteiBackpic:        INCBIN "gfx/pokemon/entei/back.2bpp.lz"
GruntfPic:           INCBIN "gfx/trainers/grunt_f.2bpp.lz"
HorseaFrontpic:      INCBIN "gfx/pokemon/horsea/front.animated.2bpp.lz"
PorygonBackpic:      INCBIN "gfx/pokemon/porygon/back.2bpp.lz"
CelebiBackpic:         INCBIN "gfx/pokemon/celebi/back.2bpp.lz"
CutieflyBackpic:    INCBIN "gfx/pokemon/cutiefly/back.2bpp.lz"
LucarioBackpic:          INCBIN "gfx/pokemon/lucario/back.2bpp.lz"
IgglybuffBackpic:       INCBIN "gfx/pokemon/igglybuff/back.2bpp.lz"
FlabebeBackpic:         INCBIN "gfx/pokemon/flabebe/back.2bpp.lz"
AerodactylBackpic:   INCBIN "gfx/pokemon/aerodactyl/back.2bpp.lz"
MimikyuFrontpic:      INCBIN "gfx/pokemon/mimikyu/front.animated.2bpp.lz"
MienshaoBackpic:      INCBIN "gfx/pokemon/mienshao/back.2bpp.lz"
QuilladinBackpic:   INCBIN "gfx/pokemon/quilladin/back.2bpp.lz"
EspurrBackpic:     INCBIN "gfx/pokemon/espurr/back.2bpp.lz"
GravelerBackpic:     INCBIN "gfx/pokemon/graveler/back.2bpp.lz"
AipomBackpic:        INCBIN "gfx/pokemon/aipom/back.2bpp.lz"
EspeonxBackpic:       INCBIN "gfx/pokemon/espeon/back.2bpp.lz"
LycanrocFrontpic:      INCBIN "gfx/pokemon/lycanroc_midday/front.animated.2bpp.lz"
TotodileBackpic:     INCBIN "gfx/pokemon/totodile/back.2bpp.lz"
SnubbullBackpic:     INCBIN "gfx/pokemon/snubbull/back.2bpp.lz"
KinglerBackpic:      INCBIN "gfx/pokemon/kingler/back.2bpp.lz"
GengarBackpic:       INCBIN "gfx/pokemon/gengar/back.2bpp.lz"
Porygon2Backpic:      INCBIN "gfx/pokemon/porygon2/back.2bpp.lz"
YoungsterPic:        INCBIN "gfx/trainers/youngster.2bpp.lz"
WillPic:             INCBIN "gfx/trainers/will.2bpp.lz"
SchoolboyPic:        INCBIN "gfx/trainers/schoolboy.2bpp.lz"
Placeholder1Frontpic:   INCBIN "gfx/pokemon/placeholder1/front.animated.2bpp.lz"


SECTION "Pics 16", ROMX

ErikaPic:            INCBIN "gfx/trainers/erika.2bpp.lz"
JaninePic:           INCBIN "gfx/trainers/janine.2bpp.lz"
Placeholder1Backpic:    INCBIN "gfx/pokemon/placeholder1/back.2bpp.lz"
TyranitarBackpic:     INCBIN "gfx/pokemon/tyranitar/back.2bpp.lz"
NoctowlBackpic:      INCBIN "gfx/pokemon/noctowl/back.2bpp.lz"
MortyPic:            INCBIN "gfx/trainers/morty.2bpp.lz"
ExcadrillBackpic:       INCBIN "gfx/pokemon/excadrill/back.2bpp.lz"
KabutoBackpic:       INCBIN "gfx/pokemon/kabuto/back.2bpp.lz"
ChesnaughtBackpic:   INCBIN "gfx/pokemon/chesnaught/back.2bpp.lz"
HawluchaBackpic:       INCBIN "gfx/pokemon/hawlucha/back.2bpp.lz"
MeganiumBackpic:     INCBIN "gfx/pokemon/meganium/back.2bpp.lz"
PicnickerPic:        INCBIN "gfx/trainers/picnicker.2bpp.lz"
LickitungBackpic:    INCBIN "gfx/pokemon/lickitung/back.2bpp.lz"
HeidreigonFrontpic:      INCBIN "gfx/pokemon/heidreigon/front.animated.2bpp.lz"
SuperNerdPic:        INCBIN "gfx/trainers/super_nerd.2bpp.lz"
HaunterBackpic:      INCBIN "gfx/pokemon/haunter/back.2bpp.lz"
TyphlosionBackpic:         INCBIN "gfx/pokemon/typhlosion/back.2bpp.lz"
RedPic:              INCBIN "gfx/trainers/red.2bpp.lz"
LampentBackpic:     INCBIN "gfx/pokemon/lampent/back.2bpp.lz"
JasminePic:          INCBIN "gfx/trainers/jasmine.2bpp.lz"
PinecoBackpic:       INCBIN "gfx/pokemon/pineco/back.2bpp.lz"
ZoroarkFrontpic:     INCBIN "gfx/pokemon/zoroark/front.animated.2bpp.lz"
SeelBackpic:         INCBIN "gfx/pokemon/seel/back.2bpp.lz"
QuagsireBackpic:     INCBIN "gfx/pokemon/quagsire/back.2bpp.lz"
WhitneyPic:          INCBIN "gfx/trainers/whitney.2bpp.lz"
JolteonxBackpic:      INCBIN "gfx/pokemon/jolteon/back.2bpp.lz"
ZoruaFrontpic:    INCBIN "gfx/pokemon/zorua/front.animated.2bpp.lz"
HoppipBackpic:       INCBIN "gfx/pokemon/hoppip/back.2bpp.lz"
BluePic:             INCBIN "gfx/trainers/blue.2bpp.lz"
GranbullBackpic:     INCBIN "gfx/pokemon/granbull/back.2bpp.lz"
GentlemanPic:        INCBIN "gfx/trainers/gentleman.2bpp.lz"
ExecutivemPic:       INCBIN "gfx/trainers/executive_m.2bpp.lz"
MeowthBackpic:      INCBIN "gfx/pokemon/meowth/back.2bpp.lz"
SunkernBackpic:      INCBIN "gfx/pokemon/sunkern/back.2bpp.lz"
LaprasBackpic:       INCBIN "gfx/pokemon/lapras/back.2bpp.lz"
ZapdosBackpic:        INCBIN "gfx/pokemon/magby/back.2bpp.lz"
DragonairBackpic:    INCBIN "gfx/pokemon/dragonair/back.2bpp.lz"
CrustleBackpic:       INCBIN "gfx/pokemon/crustle/back.2bpp.lz"
ChikoritaBackpic:    INCBIN "gfx/pokemon/chikorita/back.2bpp.lz"
GolurkBackpic:      INCBIN "gfx/pokemon/golurk/back.2bpp.lz"
ChinchouBackpic:     INCBIN "gfx/pokemon/chinchou/back.2bpp.lz"
ChanseyBackpic:      INCBIN "gfx/pokemon/chansey/back.2bpp.lz"
SkiploomBackpic:     INCBIN "gfx/pokemon/skiploom/back.2bpp.lz"
SpinarakFrontpic:    INCBIN "gfx/pokemon/spinarak/front.animated.2bpp.lz"
Rival2Pic:           INCBIN "gfx/trainers/rival2.2bpp.lz"
UnownWFrontpic:      INCBIN "gfx/pokemon/unown_w/front.animated.2bpp.lz"
FlareonxBackpic:   INCBIN "gfx/pokemon/flareon/back.2bpp.lz"
RhyhornBackpic:      INCBIN "gfx/pokemon/rhyhorn/back.2bpp.lz"
UnownCFrontpic:      INCBIN "gfx/pokemon/unown_c/front.animated.2bpp.lz"
MistyPic:            INCBIN "gfx/trainers/misty.2bpp.lz"
BlainePic:           INCBIN "gfx/trainers/blaine.2bpp.lz"


SECTION "Pics 17", ROMX

UnownZFrontpic:      INCBIN "gfx/pokemon/unown_z/front.animated.2bpp.lz"
ClaydolFrontpic:      INCBIN "gfx/pokemon/claydol/front.animated.2bpp.lz"
LatiosBackpic:     INCBIN "gfx/pokemon/latios/back.2bpp.lz"
Place3Backpic:      INCBIN "gfx/pokemon/place3/back.2bpp.lz"
UnownHBackpic:       INCBIN "gfx/pokemon/unown_h/back.2bpp.lz"
SentretBackpic:        INCBIN "gfx/pokemon/sentret/back.2bpp.lz"
VaporeonxBackpic:     INCBIN "gfx/pokemon/vaporeon/back.2bpp.lz"
DeerlingBackpic:    INCBIN "gfx/pokemon/deerling/back.2bpp.lz"
ExecutivefPic:       INCBIN "gfx/trainers/executive_f.2bpp.lz"
EeveexBackpic:    INCBIN "gfx/pokemon/eevee/back.2bpp.lz"
DusknoirBackpic:     INCBIN "gfx/pokemon/dusknoir/back.2bpp.lz"
PichuBackpic:        INCBIN "gfx/pokemon/pichu/back.2bpp.lz"
BisharpBackpic:     INCBIN "gfx/pokemon/bisharp/back.2bpp.lz"
ChespinBackpic:   INCBIN "gfx/pokemon/chespin/back.2bpp.lz"
GrimerBackpic:       INCBIN "gfx/pokemon/grimer/back.2bpp.lz"
LanturnBackpic:      INCBIN "gfx/pokemon/lanturn/back.2bpp.lz"
MagnezoneBackpic:    INCBIN "gfx/pokemon/magnezone/back.2bpp.lz"
StaryuBackpic:       INCBIN "gfx/pokemon/staryu/back.2bpp.lz"
MrMimeBackpic:       INCBIN "gfx/pokemon/mr__mime/back.2bpp.lz"
ZoruaBackpic:     INCBIN "gfx/pokemon/zorua/back.2bpp.lz"
VoltorbFrontpic:     INCBIN "gfx/pokemon/voltorb/front.animated.2bpp.lz"
ShayminBackpic:        INCBIN "gfx/pokemon/shaymin/back.2bpp.lz"
PrycePic:            INCBIN "gfx/trainers/pryce.2bpp.lz"
BrockPic:            INCBIN "gfx/trainers/brock.2bpp.lz"
UnownGFrontpic:      INCBIN "gfx/pokemon/unown_g/front.animated.2bpp.lz"
TogeticBackpic:        INCBIN "gfx/pokemon/togetic/back.2bpp.lz"
DragoniteBackpic:    INCBIN "gfx/pokemon/dragonite/back.2bpp.lz"
HitmonleeBackpic:    INCBIN "gfx/pokemon/hitmonlee/back.2bpp.lz"
QuilavaFrontpic:        INCBIN "gfx/pokemon/quilava/front.animated.2bpp.lz"
DrillburBackpic:     INCBIN "gfx/pokemon/drillbur/back.2bpp.lz"
SagePic:             INCBIN "gfx/trainers/sage.2bpp.lz"
SigilyphBackpic:    INCBIN "gfx/pokemon/sigilyph/back.2bpp.lz"
CofagrigusBackpic:       INCBIN "gfx/pokemon/cofagrigus/back.2bpp.lz"
UnownVFrontpic:      INCBIN "gfx/pokemon/unown_v/front.animated.2bpp.lz"
MimikyuBackpic:       INCBIN "gfx/pokemon/mimikyu/back.2bpp.lz"
WobbuffetBackpic:    INCBIN "gfx/pokemon/wobbuffet/back.2bpp.lz"
HeidreigonBackpic:       INCBIN "gfx/pokemon/heidreigon/back.2bpp.lz"
CrobatBackpic:       INCBIN "gfx/pokemon/crobat/back.2bpp.lz"
SuicuneBackpic:      INCBIN "gfx/pokemon/suicune/back.2bpp.lz"
IncineroarBackpic:     INCBIN "gfx/pokemon/incineroar/back.2bpp.lz"
ZweilousBackpic:    INCBIN "gfx/pokemon/zweilous/back.2bpp.lz"
DelphoxBackpic:    INCBIN "gfx/pokemon/delphox/back.2bpp.lz"
BronzongBackpic:    INCBIN "gfx/pokemon/bronzong/back.2bpp.lz"
UnownSFrontpic:      INCBIN "gfx/pokemon/unown_s/front.animated.2bpp.lz"
HorseaBackpic:       INCBIN "gfx/pokemon/horsea/back.2bpp.lz"
LarvitarBackpic:      INCBIN "gfx/pokemon/larvitar/back.2bpp.lz"
UnownOFrontpic:      INCBIN "gfx/pokemon/unown_o/front.animated.2bpp.lz"
UnownTFrontpic:      INCBIN "gfx/pokemon/unown_t/front.animated.2bpp.lz"
NidorinoBackpic:   INCBIN "gfx/pokemon/nidorino/back.2bpp.lz"
DwebbleBackpic:     INCBIN "gfx/pokemon/dwebble/back.2bpp.lz"
DewpiderBackpic:        INCBIN "gfx/pokemon/dewpider/back.2bpp.lz"
LycanrocBackpic:       INCBIN "gfx/pokemon/lycanroc_midday/back.2bpp.lz"
UnownHFrontpic:      INCBIN "gfx/pokemon/unown_h/front.animated.2bpp.lz"
CleffaBackpic:       INCBIN "gfx/pokemon/cleffa/back.2bpp.lz"
DrowzeeBackpic:      INCBIN "gfx/pokemon/drowzee/back.2bpp.lz"
GastlyBackpic:       INCBIN "gfx/pokemon/gastly/back.2bpp.lz"
PersianBackpic:       INCBIN "gfx/pokemon/persian/back.2bpp.lz"
BraixenBackpic:       INCBIN "gfx/pokemon/braixen/back.2bpp.lz"


SECTION "Pics 18", ROMX

DratiniBackpic:      INCBIN "gfx/pokemon/dratini/back.2bpp.lz"
ElectrodeBackpic:    INCBIN "gfx/pokemon/electrode/back.2bpp.lz"
AegislashBackpic:     INCBIN "gfx/pokemon/aegislash/back.2bpp.lz"
ZoroarkBackpic:      INCBIN "gfx/pokemon/zoroark/back.2bpp.lz"
Nidoran_MBackpic:   INCBIN "gfx/pokemon/nidoran_m/back.2bpp.lz"
NidoqueenBackpic:       INCBIN "gfx/pokemon/nidoqueen/back.2bpp.lz"
UnownDBackpic:       INCBIN "gfx/pokemon/unown_d/back.2bpp.lz"
SpinarakBackpic:     INCBIN "gfx/pokemon/spinarak/back.2bpp.lz"
RaikouBackpic:       INCBIN "gfx/pokemon/raikou/back.2bpp.lz"
UnownKFrontpic:      INCBIN "gfx/pokemon/unown_k/front.animated.2bpp.lz"
SandslashBackpic:      INCBIN "gfx/pokemon/sandslash/back.2bpp.lz"
PawniardBackpic:     INCBIN "gfx/pokemon/pawniard/back.2bpp.lz"
LeafeonBackpic:     INCBIN "gfx/pokemon/leafeon/back.2bpp.lz"
UnownBackpic:      INCBIN "gfx/pokemon/unown/back.2bpp.lz"
DewgongBackpic:      INCBIN "gfx/pokemon/dewgong/back.2bpp.lz"
UnownBFrontpic:      INCBIN "gfx/pokemon/unown_b/front.animated.2bpp.lz"
SlowpokeBackpic:     INCBIN "gfx/pokemon/slowpoke/back.2bpp.lz"
DunsparceBackpic:    INCBIN "gfx/pokemon/dunsparce/back.2bpp.lz"
LitwickBackpic:      INCBIN "gfx/pokemon/litwick/back.2bpp.lz"
WooperBackpic:       INCBIN "gfx/pokemon/wooper/back.2bpp.lz"
TaurosBackpic:       INCBIN "gfx/pokemon/tauros/back.2bpp.lz"
UnownXFrontpic:      INCBIN "gfx/pokemon/unown_x/front.animated.2bpp.lz"
UnownNFrontpic:      INCBIN "gfx/pokemon/unown_n/front.animated.2bpp.lz"
TangelaBackpic:      INCBIN "gfx/pokemon/tangela/back.2bpp.lz"
VoltorbBackpic:      INCBIN "gfx/pokemon/voltorb/back.2bpp.lz"
UnownJFrontpic:      INCBIN "gfx/pokemon/unown_j/front.animated.2bpp.lz"
DoubladeBackpic:      INCBIN "gfx/pokemon/doublade/back.2bpp.lz"
UnownLFrontpic:      INCBIN "gfx/pokemon/unown_l/front.animated.2bpp.lz"
GolettBackpic:    INCBIN "gfx/pokemon/golett/back.2bpp.lz"
UnownMFrontpic:      INCBIN "gfx/pokemon/unown_m/front.animated.2bpp.lz"
UnownFFrontpic:      INCBIN "gfx/pokemon/unown_f/front.animated.2bpp.lz"
QuilavaBackpic:         INCBIN "gfx/pokemon/quilava/back.2bpp.lz"
UnownAFrontpic:      INCBIN "gfx/pokemon/unown_a/front.animated.2bpp.lz"
GolemBackpic:        INCBIN "gfx/pokemon/golem/back.2bpp.lz"
UnownUFrontpic:      INCBIN "gfx/pokemon/unown_u/front.animated.2bpp.lz"
MienfooBackpic:      INCBIN "gfx/pokemon/mienfoo/back.2bpp.lz"
UnownQFrontpic:      INCBIN "gfx/pokemon/unown_q/front.animated.2bpp.lz"
UnownPFrontpic:      INCBIN "gfx/pokemon/unown_p/front.animated.2bpp.lz"
UnownCBackpic:       INCBIN "gfx/pokemon/unown_c/back.2bpp.lz"
JynxBackpic:         INCBIN "gfx/pokemon/jynx/back.2bpp.lz"
NidokingBackpic:       INCBIN "gfx/pokemon/nidoking/back.2bpp.lz"
UnownYFrontpic:      INCBIN "gfx/pokemon/unown_y/front.animated.2bpp.lz"
UnownGBackpic:       INCBIN "gfx/pokemon/unown_g/back.2bpp.lz"
UnownIFrontpic:      INCBIN "gfx/pokemon/unown_i/front.animated.2bpp.lz"
UnownVBackpic:       INCBIN "gfx/pokemon/unown_v/back.2bpp.lz"
ForretressBackpic:   INCBIN "gfx/pokemon/forretress/back.2bpp.lz"
UnownSBackpic:       INCBIN "gfx/pokemon/unown_s/back.2bpp.lz"
UnownRFrontpic:      INCBIN "gfx/pokemon/unown_r/front.animated.2bpp.lz"
UnownEBackpic:       INCBIN "gfx/pokemon/unown_e/back.2bpp.lz"
UnownJBackpic:       INCBIN "gfx/pokemon/unown_j/back.2bpp.lz"
UnownBBackpic:       INCBIN "gfx/pokemon/unown_b/back.2bpp.lz"
UnownOBackpic:       INCBIN "gfx/pokemon/unown_o/back.2bpp.lz"
UnownZBackpic:       INCBIN "gfx/pokemon/unown_z/back.2bpp.lz"
UnownWBackpic:       INCBIN "gfx/pokemon/unown_w/back.2bpp.lz"
UnownNBackpic:       INCBIN "gfx/pokemon/unown_n/back.2bpp.lz"
UnownABackpic:       INCBIN "gfx/pokemon/unown_a/back.2bpp.lz"
UnownMBackpic:       INCBIN "gfx/pokemon/unown_m/back.2bpp.lz"
UnownKBackpic:       INCBIN "gfx/pokemon/unown_k/back.2bpp.lz"
UnownTBackpic:       INCBIN "gfx/pokemon/unown_t/back.2bpp.lz"
UnownXBackpic:       INCBIN "gfx/pokemon/unown_x/back.2bpp.lz"
UnownLBackpic:       INCBIN "gfx/pokemon/unown_l/back.2bpp.lz"
UnownUBackpic:       INCBIN "gfx/pokemon/unown_u/back.2bpp.lz"
UnownQBackpic:       INCBIN "gfx/pokemon/unown_q/back.2bpp.lz"
UnownYBackpic:       INCBIN "gfx/pokemon/unown_y/back.2bpp.lz"
UnownPBackpic:       INCBIN "gfx/pokemon/unown_p/back.2bpp.lz"


SECTION "Pics 19", ROMX

UnownIBackpic:              INCBIN "gfx/pokemon/unown_i/back.2bpp.lz"
UnownRBackpic:              INCBIN "gfx/pokemon/unown_r/back.2bpp.lz"
MewFrontpic: 	 		INCBIN "gfx/pokemon/mew/front.animated.2bpp.lz"
MewBackpic: 	 		INCBIN "gfx/pokemon/mew/back.2bpp.lz"
MewtwoFrontpic: 	 	INCBIN "gfx/pokemon/mewtwo/front.animated.2bpp.lz"
MewtwoBackpic: 	 	INCBIN "gfx/pokemon/mewtwo/back.2bpp.lz"

GrimerFrontpic:      	    INCBIN "gfx/pokemon/grimer/front.animated.2bpp.lz"
GrimerBackpic:       	    INCBIN "gfx/pokemon/grimer/back.2bpp.lz"
Grimer_AlolaFrontpic:      	INCBIN "gfx/pokemon/grimer_alola/front.animated.2bpp.lz"
Grimer_AlolaBackpic:       	INCBIN "gfx/pokemon/grimer_alola/back.2bpp.lz"

MukFrontpic:   	            INCBIN "gfx/pokemon/muk/front.animated.2bpp.lz"
MukBackpic:    	            INCBIN "gfx/pokemon/muk/back.2bpp.lz"
Muk_AlolaFrontpic:   	    INCBIN "gfx/pokemon/muk_alola/front.animated.2bpp.lz"
Muk_AlolaBackpic:    	    INCBIN "gfx/pokemon/muk_alola/back.2bpp.lz"

VulpixFrontpic:      	    INCBIN "gfx/pokemon/Vulpix/front.animated.2bpp.lz"
VulpixBackpic:       	    INCBIN "gfx/pokemon/Vulpix/back.2bpp.lz"
Vulpix_AlolaFrontpic:      	INCBIN "gfx/pokemon/Vulpix_alola/front.animated.2bpp.lz"
Vulpix_AlolaBackpic:       	INCBIN "gfx/pokemon/Vulpix_alola/back.2bpp.lz"

NinetalesFrontpic:   	    INCBIN "gfx/pokemon/ninetales/front.animated.2bpp.lz"
NinetalesBackpic:    	    INCBIN "gfx/pokemon/ninetales/back.2bpp.lz"
Ninetales_AlolaFrontpic:   	INCBIN "gfx/pokemon/ninetales_alola/front.animated.2bpp.lz"
Ninetales_AlolaBackpic:    	INCBIN "gfx/pokemon/ninetales_alola/back.2bpp.lz"

; Sections "Pics 20" to "Pics 24" are not used for any graphics,
; but entries for their banks exist in FixPicBank (see engine/gfx/load_pics.asm).

SECTION "Pics 20", ROMX

BeautyPortrait: 		INCBIN "gfx/portraits/beauty.2bpp.lz"
ZygardeNeutralPortrait: INCBIN "gfx/portraits/Zygarde_neutral.2bpp.lz"
ZygardeAngryPortrait: 	INCBIN "gfx/portraits/Zygarde_angry.2bpp.lz"
CelebiNeutralPortrait:  INCBIN "gfx/portraits/Celebi_neutral.2bpp.lz"


SECTION "Pics 21", ROMX

SECTION "Pics 22", ROMX

SECTION "Pics 23", ROMX

SECTION "Pics 24", ROMX
